#!/bin/bash

# Destroys PostgreSQL instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t stickshift_postgresql_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

app_type="postgresql-8.4"
setup_embedded_deconfigure "$1" $2 $3

source ${CART_INFO_DIR}/lib/util

PSQL_DIR="$APP_HOME/postgresql-8.4/"

#
# Teardown port proxy (ignore failures or missing hook)
#
( ${CART_INFO_DIR}/hooks/conceal-port "$1" $2 $3 ) &>/dev/null || :

#
# Remove environment variables
#
[ -f $APP_HOME/.env/OPENSHIFT_DB_TYPE ]  &&  source $APP_HOME/.env/OPENSHIFT_DB_TYPE
if [ "$OPENSHIFT_DB_TYPE" = "postgresql" ]; then
   /bin/rm -f $APP_HOME/.env/OPENSHIFT_DB_USERNAME $APP_HOME/.env/OPENSHIFT_DB_PASSWORD $APP_HOME/.env/OPENSHIFT_DB_TYPE $APP_HOME/.env/OPENSHIFT_DB_HOST $APP_HOME/.env/OPENSHIFT_DB_PORT $APP_HOME/.env/OPENSHIFT_DB_SOCKET $APP_HOME/.env/OPENSHIFT_DB_URL $APP_HOME/.env/OPENSHIFT_DB_CTL_SCRIPT $APP_HOME/.env/OPENSHIFT_DB_POSTGRESQL_84_DUMP $APP_HOME/.env/OPENSHIFT_DB_POSTGRESQL_84_DUMP_CLEANUP $APP_HOME/.env/OPENSHIFT_DB_POSTGRESQL_84_RESTORE $APP_HOME/.env/OPENSHIFT_DB_POSTGRESQL_84_EMBEDDED_TYPE
fi

stop_postgresql

confirm_pid_gone "${PSQL_DIR}/pid/postgres.pid"

runcon -l s0-s0:c0.c1023 rm -rf "$PSQL_DIR" "$PSQL_DIR/${application}_postgresql_ctl.sh"

