#!/usr/bin/env oo-ruby
#
# openshift-routing-daemon  Starts the routing daemon for OpenShift 
#
# chkconfig:       345 89 11
# processname:     openshift-routing-daemon
#
# short-description: Starts the routing daemon for OpenShift
# description: This is a daemon which listens for notifications of
#               application lifecycle events on ActiveMQ from the
#               OpenShift routing plug-in and configures an external
#               routing appropriately.

require 'rubygems'
require 'daemons'
require 'timeout'
require 'openshift-origin-common/utils/path_utils'
require 'openshift/routing/daemon'


# load any custom configuration elements for Watchman
path = "/etc/sysconfig/watchman"
if File.exists? path
  config = ParseConfig.new path
  config.get_params.each { |k| ENV[k] = config[k] }
end

Options = {
    :backtrace => true,
    :ontop => false,
    :log_output => true,
    :dir_mode => :system,
    :multiple => false,
    :script => 'openshift-routing-daemon',
}

def daemon_running?
  %x[/usr/bin/pgrep -f '^openshift-routing-daemon']
  $?.exitstatus == 0
end

def locked
  Timeout::timeout(ENV['LOCK_TIMEOUT'] || 60) do
    PathUtils.flock('/var/lock/openshift-routing-daemon.lock') do
      yield
    end
  end
rescue Timeout::Error
  puts 'openshift-routing-daemon operation timed out'
  exit! 1
end

case ARGV[0]
  when 'stop'
    puts 'Stopping openshift-routing-daemon'
    locked  do
      Daemons.run_proc(Options[:script], Options)
    end
  when 'start'
    puts 'Starting openshift-routing-daemon'
    locked  do
      Daemons.run_proc(Options[:script], Options) do
	OpenShift::RoutingDaemon.new.listen
      end
    end
  when 'restart'
    puts 'Stopping openshift-routing-daemon'
    locked do
      loop do
        Daemons.run(Options[:script], Options.merge(ARGV: ['stop']))
        break unless daemon_running?
        sleep 1
        $stdout.write '.'
      end
      puts 'Starting openshift-routing-daemon'
      Daemons.run_proc(Options[:script], Options.merge(ARGV: ['start'])) do
	OpenShift::RoutingDaemon.new.listen
      end
    end
  when 'status'
    if daemon_running?
      puts 'openshift-routing-daemon is running'
      exit 0
    else
      puts 'openshift-routing-daemon is not running'
      exit 1
    end
  else
    locked { Daemons.run(Options[:script], Options) }
end
