#!/bin/bash

# Start the application httpd instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Start a running application"

    echo "$0 $@" | logger -p local0.notice -t stickshift_httpd_start
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

CART_NS=$(get_cartridge_namespace_from_path)
OPENSHIFT_JBOSS_CLUSTER_PORT=$(get_env_var_dynamic "OPENSHIFT_${CART_NS}_CLUSTER_PORT")

setup_configure "$1" $2 $3

import_env_vars

proxy_port=$(show_proxy_port $uuid "$OPENSHIFT_INTERNAL_IP:$OPENSHIFT_INTERNAL_PORT")
ret=$?
if [ $ret -ne 0 ]; then
  client_result "No proxy ports defined"
  exit 0
fi

cluster_port=$(find_next_proxy_port $uuid "$OPENSHIFT_INTERNAL_IP:$OPENSHIFT_JBOSS_CLUSTER_PORT")
ret=$?
if [ $ret -ne 0 ]; then
  client_result "No proxy ports defined"
  exit 0
fi

cart_data "PROXY_HOST=$OPENSHIFT_GEAR_DNS"
cart_data "PROXY_PORT=$proxy_port"
cart_data "HOST=$OPENSHIFT_INTERNAL_IP"
cart_data "PORT=$OPENSHIFT_INTERNAL_PORT"

cart_data "${CART_NS}_CLUSTER_PROXY_HOST=$OPENSHIFT_GEAR_DNS"
cart_data "${CART_NS}_CLUSTER_PROXY_PORT=$cluster_port"
cart_data "${CART_NS}_CLUSTER_HOST=$OPENSHIFT_INTERNAL_IP"
cart_data "${CART_NS}_CLUSTER_PORT=$OPENSHIFT_JBOSS_CLUSTER_PORT"

cart_data "${CART_NS}_MESSAGING_PORT=$messaging_port"
cart_data "${CART_NS}_MESSAGING_THROUGHPUT_PORT=$messaging_throughput_port"
cart_data "${CART_NS}_REMOTING_PORT=$remoting_port"


exit 0
