#!/bin/bash

# Destroys 10gen-mms-agent instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_10gen_mms_agent_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

cartridge_type="10gen-mms-agent-0.1"
source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_embedded_deconfigure "$1" $2 $3
disable_cgroups


MMS_DIR=`get_cartridge_instance_dir "$cartridge_type" | tr -s /` # ensure that there aren't double /'s

#
# Stop app
#
run_as_user "${CARTRIDGE_BASE_PATH}/${cartridge_type}/info/bin/app_ctl.sh stop" || warning "Failed to stop ${application}" 121

confirm_pid_gone "${MMS_DIR}/run/mms-agent.pid"
confirm_log_files_inactive "$MMS_DIR/logs"


# Remove 10gen mms agent dir. This MUST be after stopping the agent as the CTL script relies on these.
runcon -l s0-s0:c0.c1023 rm -rf "$MMS_DIR"
rm -f $OPENSHIFT_HOME/.env/OPENSHIFT_10GENMMSAGENT_*

enable_cgroups

