#!/bin/bash

# Gets status of instance

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Stop a running application and disable it"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_10gen_mms_agent_status
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_basic_hook "$1" $2 $3

if output=$(runuser --shell /bin/sh "$uuid" -c "if ps -ef | grep ${uuid}_agent.py | grep -qv grep > /dev/null; then echo Running; else echo Stopped; fi" 2>&1)
then
    status_client_result "$output"
else
    client_result "10gen-mms-agent is either stopped or inaccessible"
fi