#require "bundler/gem_tasks"
require 'rake'
require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.warning = false
  t.verbose = true
  t.test_files = FileList['test/**/*_test.rb']
end
