#!/bin/bash

# Destroys mysql instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t stickshift_mysql_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/git

app_type="mysql-5.1"
setup_embedded_deconfigure "$1" $2 $3

CART_INFO_DIR=${CARTRIDGE_BASE_PATH}/embedded/mysql-5.1/info
source ${CART_INFO_DIR}/lib/util

MYSQL_DIR="$APP_HOME/mysql-5.1/"

source_if_exists "$APP_HOME/.env/OPENSHIFT_GEAR_TYPE"
source_if_exists "$APP_HOME/.env/OPENSHIFT_DB_TYPE"

#
# Teardown port proxy (ignore failures or missing hook)
#
( ${CART_INFO_DIR}/hooks/conceal-port "$1" $2 $3 ) &>/dev/null || :


# For non-embedded (dedicated) mysql gear, destroy the git repo and stop app.
if [ "mysql-5.1" = "$OPENSHIFT_GEAR_TYPE" ]; then
   remove_all_proxy_ports $uuid

   # Destroy git repo and stop app.
   destroy_git_repo $application $uuid
   stop_app
fi

# Stop mysql before we remove all the variables.
stop_mysql
confirm_pid_gone "${MYSQL_DIR}/pid/mysql.pid"

#
# Remove environment variables
#
if [ "$OPENSHIFT_DB_TYPE" = "mysql" ]; then
   /bin/rm -f $APP_HOME/.env/OPENSHIFT_DB_USERNAME $APP_HOME/.env/OPENSHIFT_DB_PASSWORD $APP_HOME/.env/OPENSHIFT_DB_TYPE $APP_HOME/.env/OPENSHIFT_DB_HOST $APP_HOME/.env/OPENSHIFT_DB_PORT $APP_HOME/.env/OPENSHIFT_DB_SOCKET $APP_HOME/.env/OPENSHIFT_DB_URL $APP_HOME/.env/OPENSHIFT_DB_CTL_SCRIPT $APP_HOME/.env/OPENSHIFT_DB_MYSQL_51_DUMP $APP_HOME/.env/OPENSHIFT_DB_MYSQL_51_DUMP_CLEANUP $APP_HOME/.env/OPENSHIFT_DB_MYSQL_51_RESTORE $APP_HOME/.env/OPENSHIFT_DB_MYSQL_51_EMBEDDED_TYPE $APP_HOME/.env/OPENSHIFT_DB_MYSQL_51_PROFILE
fi

runcon -l s0-s0:c0.c1023 rm -rf "$MYSQL_DIR" "$MYSQL_DIR/${application}_mysql_ctl.sh"

# For non-embedded (dedicated) mysql gear, destroy the gear.
if [ "mysql-5.1" = "$OPENSHIFT_GEAR_TYPE" ]; then
    # Blow away the directories.
    rm_app_dir
    rm_unobfuscated_app_home $namespace $application

    # Remove apache vhost configuration.
    rm_httpd_proxy $uuid $namespace $application
fi
