#!/bin/bash

# Restarts instance

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Get application status"

    echo "$0 $@" | logger -p local0.notice -t stickshift_mysql_restart
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

cartridge_type="mysql-5.1"
source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_basic_hook "$1" $2 $3

MYSQL_DIR=$(get_cartridge_instance_dir "$cartridge_type")


#
# Restart application
#
rm -f "$MYSQL_DIR/run/stop_lock"
super_run_as_user "$MYSQL_DIR/${application}_mysql_ctl.sh restart"
