#!/bin/bash

# Import Environment Variables
for f in ~/.env/*
do
    . $f
done

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

JBOSS_DIR="$OPENSHIFT_HOMEDIR/jbossas-7/jbossas-7"

# Clean up logs
for logdir in `awk 'BEGIN {
                           for (a in ENVIRON)
                           if (a ~ /LOG_DIR$/)
                           print ENVIRON[a] }'`
do
    client_message "Emptying log dir: ${logdir}"
    rm -rf ${logdir}* ${logdir}.[^.]*
done


standalone_tmp=${JBOSS_DIR}/standalone/tmp/
if [ -d $standalone_tmp ]
then
    client_message "Emptying tmp dir: $standalone_tmp"
    rm -rf $standalone_tmp/* $standalone_tmp/.[^.]*
fi
