#!/bin/bash

# Give status of application

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Get application status"

    echo "$0 $@" | logger -p local0.notice -t stickshift_jenkins_status
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_basic_hook "$1" $2 $3

#
# Check application status
#
if output=$(run_as_user "$APP_DIR/${application}_ctl.sh status" 2>&1)
then
    status_client_result "$output"
else
    client_result "Application '${application}' is either stopped or inaccessible"
fi
send_stopped_status
send_quotas
