#!/bin/bash -eu

cartridge_instance_dir=$OPENSHIFT_MOCK_DIR
source $cartridge_instance_dir/mock.conf

touch $MOCK_STATE/publish-db-connection-info_called

echo "OPENSHIFT_MOCK_DB_USERNAME=UT_username;\
 OPENSHIFT_MOCK_DB_PASSWORD=UT_password;\
 OPENSHIFT_MOCK_DB_HOST=$OPENSHIFT_MOCK_EXAMPLE_IP1;\
 OPENSHIFT_MOCK_DB_PORT=$OPENSHIFT_MOCK_EXAMPLE_PORT1;\
 OPENSHIFT_MOCK_DB_URL=mock://${OPENSHIFT_MOCK_EXAMPLE_IP1}:${OPENSHIFT_MOCK_EXAMPLE_PORT1}/unit_test;"
exit 0
