#!/usr/bin/env oo-ruby

require 'rubygems'
require 'getoptlong'

CTL_APP_COMMANDS = "(start|stop|force-stop|restart|status|destroy|force-destroy|remove-gear|remove-cartridge)"

def usage
  puts <<USAGE
== Synopsis

oo-admin-ctl-app: Control user applications

== Usage

oo-admin-ctl-app OPTIONS

Options:
-l|--login <login_name>
    Login with OpenShift access (required)
-a|--app     <application>
    Application name  (alphanumeric) (required)
-c|--command <command>
    #{CTL_APP_COMMANDS} (required)
-b|--bypass
    Ignore warnings
--gear_uuid
    Gear uuid to operate on
--cartridge
    Cartridge to operate on
-h|--help
    Show Usage info
USAGE
  exit 255
end

opts = GetoptLong.new(
    ["--login",            "-l", GetoptLong::REQUIRED_ARGUMENT],
    ["--app",              "-a", GetoptLong::REQUIRED_ARGUMENT],    
    ["--command",          "-c", GetoptLong::REQUIRED_ARGUMENT],
    ["--gear_uuid",              GetoptLong::REQUIRED_ARGUMENT],
    ["--cartridge",              GetoptLong::REQUIRED_ARGUMENT],
    ["--bypass",           "-b", GetoptLong::NO_ARGUMENT],    
    ["--help",             "-h", GetoptLong::NO_ARGUMENT]
)

args = {}
begin
  opts.each{ |k,v| args[k]=v }
rescue GetoptLong::Error => e
  usage
end

login    = args["--login"]
app_name = args["--app"]
command  = args['--command']
bypass   = args['--bypass']
gear_uuid = args['--gear_uuid']
cartridge = args['--cartridge']

if login.nil? or app_name.nil? or command.nil? or args["--help"]
  usage
end

require "/var/www/openshift/broker/config/environment"
# Disable analytics for admin scripts
Rails.configuration.analytics[:enabled] = false

user = CloudUser.find_by(login: login)
unless user
  puts "User #{login} not found."
  exit 1
end
app = Application.find(user,app_name)
unless app
  puts "Application #{app_name} for user #{login} not found."
  exit 1
end

def check_user_response
  begin
    agree = gets.chomp
    if agree != 'y'
      puts "\n"
      exit 217
    end
  rescue Interrupt
    puts "\n"
    exit 217
  end
end

reply = ResultIO.new
case command
when "start"
  reply.append app.start
when "stop"
  reply.append app.stop  
when "force-stop"
  reply.append app.force_stop  
when "restart"
  reply.append app.restart  
when "status"
  reply.append app.status  
when "force-destroy"
  unless bypass
    puts <<-WARNING
  !!!! WARNING !!!! WARNING !!!! WARNING !!!!
  You are about to destroy the #{app_name} application.

  This is NOT reversible, all remote data for this application will be forcefully removed.
  WARNING

    print "Do you want to forcefully destroy this application (y/n): "
    check_user_response
  end
  
  begin
    reply.append app.cleanup_and_delete
    reply.resultIO << "Successfully destroyed application: #{app.name}" if reply.resultIO.string.empty?
  rescue Exception=>e
    reply = ResultIO.new
    user = CloudUser.find_by(login: login)
    app = Application.find(user,app_name)
    current_consumed_gears = user.consumed_gears
    gear_count = app.gears.length
    app.gears.each { |g|
      begin
        g.destroy
      rescue Exception=>e
        puts "WARNING: Check gear #{g.uuid} on node '#{g.server_identity}', because destroy did not succeed cleanly. The gear may exist on node, but not in database."
      end
    }
    app.delete
    user = CloudUser.find_by(login: login)
    new_consumed_gears = user.consumed_gears
    if new_consumed_gears!=(current_consumed_gears-gear_count)
      puts "WARNING: Please check and fix the user's consumed_gear count vs the actual gears consumed, as they may be out of sync."
    end
  end
when "destroy"
  unless bypass
    puts <<-WARNING
  !!!! WARNING !!!! WARNING !!!! WARNING !!!!
  You are about to destroy the #{app_name} application.

  This is NOT reversible, all remote data for this application will be removed.
  WARNING

    print "Do you want to destroy this application (y/n): "
    check_user_response
  end
  
  reply.append app.cleanup_and_delete
  reply.resultIO << "Successfully destroyed application: #{app.name}" if reply.resultIO.string.empty?
when "remove-cartridge"
  unless cartridge
    puts "Cartridge is required to remove-dependency"
    exit 1
  end
  reply.append app.remove_dependency(cartridge)
when "remove-gear"
  unless gear_uuid
    puts "Gear uuid is required to remove-gear"
    exit 1
  end
  result_io = ResultIO.new
  comp_name = "web"
  prof = app.profile_name_map[app.default_profile]
  cinst = ComponentInstance::find_component_in_cart(prof, app, comp_name, app.get_name_prefix)
  if cinst.nil?
    puts "ERROR: Cannot find #{comp_name} in app #{app.name}." 
    exit 1
  end
  ginst = app.group_instance_map[cinst.group_instance_name]
  if ginst.nil?
    puts "ERROR: Cannot find group #{cinst.group_instance_name} for #{comp_name} in app #{app.name}." 
    exit 1
  end
  # remove any gear out of this ginst
  if ginst.gears.length <= ginst.min
    puts "ERROR: Cannot scale below minimum gear requirements" 
    exit 1
  end

  gear = ginst.gears.find { |g| g.uuid == gear_uuid }

  if gear.nil?
    puts "ERROR: Gear '#{gear_uuid}' is not one of the scaled gears of the app #{app.name}. Possible ones are #{ginst.gears.map{ |g| g.uuid }.inspect }. Please provide a valid gear with --gear_uuid option."
    exit 1
  end

  dns = OpenShift::DnsService.instance
  begin
    dns.deregister_application(gear.name, app.domain.namespace)
    dns.publish
  ensure
    dns.close
  end

  begin
    result_io.append ginst.remove_gear(gear)
  rescue Exception => e
    # pass, this might be a broken gear
  end

  # inform anyone who needs to know that this gear is no more
  app.configure_dependencies
  app.execute_connections
  reply.append result_io
else
  puts "Command must be one of: #{CTL_APP_COMMANDS}"
  usage
end

puts "DEBUG OUTPUT:\n#{reply.debugIO.string}\n" unless reply.debugIO.string.empty?
puts "ERROR OUTPUT:\n#{reply.errorIO.string}\n" unless reply.errorIO.string.empty?
puts reply.resultIO.string.empty? ? "Success" : reply.resultIO.string
