#!/bin/bash

set -e

dump=$1
user=$2
pass=$3

if [ "z${dump}" == "z" ]; then
  echo "Input file required."
  echo "Usage :"
  echo "  $0 <input file> [user] [pass]"
  exit 1
fi

echo "Extracting analytics from $dump"
TEMP=`mktemp -d`
cp $dump $TEMP
cd $TEMP
tar xvzf $dump >& /dev/null

if [ ! -d "${TEMP}/tmp/analytics" ]; then
  echo "Invalid input dump"
fi

if [ "z${user}" == "z" ] && [ "z${pass}" == "z" ]; then
    mongoimport --file ${TEMP}/tmp/analytics/analytics.apps.json --db analytics --collection applications --upsert
    mongoimport --file ${TEMP}/tmp/analytics/analytics.domains.json --db analytics --collection domains --upsert
    mongoimport --file ${TEMP}/tmp/analytics/analytics.users.json --db analytics --collection cloud_users --upsert
else
    mongoimport -u ${user} -p ${pass} --file ${TEMP}/tmp/analytics/analytics.apps.json --db analytics --collection applications --upsert
    mongoimport -u ${user} -p ${pass} --file ${TEMP}/tmp/analytics/analytics.domains.json --db analytics --collection domains --upsert
    mongoimport -u ${user} -p ${pass} --file ${TEMP}/tmp/analytics/analytics.users.json --db analytics --collection cloud_users --upsert
fi

rm -rf ${TEMP}

echo
echo "Import complete!"
