#!/bin/bash

# Import Environment Variables
for f in ~/.env/*
do
    . $f
done

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

if [ -d $OPENSHIFT_RUBY_LOG_DIR ]
then
    client_message "Emptying log dir: ${OPENSHIFT_RUBY_LOG_DIR}"
    rm -rf ${OPENSHIFT_RUBY_LOG_DIR}/* ${OPENSHIFT_RUBY_LOG_DIR}/.[^.]*
fi

if [ -d ${OPENSHIFT_REPO_DIR}tmp/ ]
then
    client_message "Emptying tmp dir: ${OPENSHIFT_REPO_DIR}tmp/"
    rm -rf ${OPENSHIFT_REPO_DIR}tmp/* ${OPENSHIFT_REPO_DIR}tmp/.[^.]*
fi