#require "bundler/gem_tasks"
require 'rake'
require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
end

require "../../../tasks/build_tasks"
require "../../../tasks/yard_tasks"
