#!/bin/bash

# Publishes the postgresql database connection information.

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Publish postgresql database connection information"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_postgresql_publish_conn_info
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source /etc/openshift/node.conf
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

for v in "OPENSHIFT_POSTGRESQL_DB_GEAR_UUID" "OPENSHIFT_POSTGRESQL_DB_GEAR_DNS" "OPENSHIFT_POSTGRESQL_DB_USERNAME" \
         "OPENSHIFT_POSTGRESQL_DB_PASSWORD"  "OPENSHIFT_POSTGRESQL_DB_HOST"     "OPENSHIFT_POSTGRESQL_DB_PORT" \
         "OPENSHIFT_POSTGRESQL_DB_URL"       "OPENSHIFT_POSTGRESQL_DB_SOCKET"
do
    app_remove_env_var $v
done
