#!/bin/bash
# openshift-iptables-port-proxy
#
# chkconfig:  2345 09 93
# description: Script to apply the openshift port proxy iptables rules.
#
### BEGIN INIT INFO
# Provides: openshift-iptables-port-proxy
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description:  Script to apply the openshift port proxy iptables rules.
# Description: Script to apply the openshift port proxy iptables rules.
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

/usr/sbin/oo-admin-ctl-iptables-port-proxy $@