#!/bin/sh
#
# openshift-tc This shell script initializes openshift traffic control for users
#
# Author:       Mark lamourine <markllama@redhat.com>
# Liberally excerpted from an example by Scott Seong
#   http://www.topwebhosts.org/tools/traffic-control.php
#
# chkconfig:    345 11 89
#
# description:  Set OpenShift traffic control limits
# processname:  NA
#

# CAVEAT: if the policy is changed, must run these by hand (release ticket)

/usr/sbin/oo-admin-ctl-tc $@

exit $?
