#!/bin/bash
# openshift-iptables-port-proxy
#
# chkconfig:  2345 11 89
# description: Script to apply the openshift port proxy iptables rules.
#
### BEGIN INIT INFO
# Provides: openshift-iptables-port-proxy
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description:  Script to apply the openshift port proxy iptables rules.
# Description: Script to apply the openshift port proxy iptables rules.
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

ROUTE_LOCALNET=`sysctl -n net.ipv4.conf.all.route_localnet`
if [ $ROUTE_LOCALNET -eq "0" ]; then
    echo "WARNING: net.ipv4.conf.all.route_localnet must be enabled." 1>&2
    echo 1 > /proc/sys/net/ipv4/conf/all/route_localnet
    echo "WARNING: It has been temporarily enabled.  Please ensure this setting is persisted in /etc/sysctl.conf."
fi

/usr/sbin/oo-admin-ctl-iptables-port-proxy $@
