#!/bin/bash

source "/etc/openshift/node.conf"

# Constants.
SERVICE_NAME=cron
CART_NAME=cron
CART_VERSION=1.4
CART_DIRNAME=${CART_NAME}-$CART_VERSION
CART_INSTALL_DIR=${CARTRIDGE_BASE_PATH}
CART_INFO_DIR=${CARTRIDGE_BASE_PATH}/embedded/$CART_DIRNAME/info

$CART_INFO_DIR/bin/scheduled-jobs run daily
