$ORIGIN .
$TTL 1	; 1 seconds (for testing only)
example.com		IN SOA	ns1.example.com. hostmaster.example.com. (
				2011112904 ; serial
				60         ; refresh (1 minute)
				15         ; retry (15 seconds)
				1800       ; expire (30 minutes)
				10         ; minimum (10 seconds)
				)
			NS	ns1.example.com.
			MX	10 mail.example.com.
$ORIGIN example.com.
mail			A	127.0.0.1
master			A	192.168.1.1
ns1			A	127.0.0.1
node                    A       192.168.1.10

; test records
testns1			TXT	"reserved namespace testns1"
;testns2		TXT	"to be added by tests"
testns3                 TXT     "reserved to add apps"
testns4                 TXT     "reserved to delete apps"
testapp4-testns4        CNAME   node.example.com.
