source 'https://rubygems.org'

# Fedora 19 splits psych out into its own gem.
if Gem::Specification.respond_to?(:find_all_by_name) and not Gem::Specification::find_all_by_name('psych').empty?
  gem 'psych'
end

gem 'openshift-origin-console', :require => 'console', :path => ENV['CONSOLE_PATH']

gem 'rake', '> 0.9.2'
gem 'pry', :require => 'pry' if ENV['PRY']
gem 'perftools.rb', :require => 'perftools' if ENV['PERFTOOLS']
gem 'syslog-logger', '~> 1.6.8', :require => false

# NON-RUNTIME BEGIN

# To simplify the packaging burden for distro maintainers it's important to
# place all gems not needed at runtime in this section.  It can be removed
# during package build time to avoid having to ship/support development-only
# packages.
group :test do
  gem 'ci_reporter',   '>= 1.7.0', :require => false
  gem 'minitest',      '>= 3.5.0', :require => false
end

# NON-RUNTIME END

group :assets do
  gem 'compass-rails', '~> 1.0.3'
  gem 'sass-rails',    '~> 3.2.5'
  gem 'coffee-rails',  '~> 3.2.2'
  gem 'jquery-rails',  '~> 3.1.0'
  gem 'uglifier',      '>= 1.2.6'
  gem 'therubyracer',  '>= 0.10'
  gem 'sass-twitter-bootstrap', '2.0.1'
  gem 'minitest',      '>= 3.5.0'
end

# Load extra gems specified in the console configuration file
begin
  conf_file_path = (ENV['OPENSHIFT_CONF_DIR'] || "/etc/openshift/") + 'console.conf'
  if File.exists?(conf_file_path)
    # Read file as binary to avoid encoding issues when configuration
    # file is encoded as UTF-8
    conf_file = File.open(conf_file_path, 'rb')
    additional_gems = conf_file.read[/^ADDITIONAL_RUBYGEMS\s*=\s*(.+)/, 1]
    if additional_gems
      gem_list = additional_gems.split(" ").uniq
      gem_list.each do |name|
        gem name.gsub(/["']/, "")
      end
    end
  else
    $stderr.puts "Could not find console configuration file at #{conf_file_path}. Skipping loading additional gems."
  end
rescue => e
  $stderr.puts "Could not parse additional gems for console: #{e.message}"
  $stderr.puts e.backtrace
  $stderr.puts "Skipping loading additional gems for console."
end
