# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
require 'rake'

RedHatCloud::Application.load_tasks
namespace :console do
  Console::Engine.load_tasks
end
