#!/bin/bash

# Move to a new ip

# Exit on any errors
set -e

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/apache
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/network

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3

setup_basic_vars

CART_INFO_DIR=${CARTRIDGE_BASE_PATH}/embedded/mongodb-2.0/info
source ${CART_INFO_DIR}/lib/util

MONGODB_DIR="$APP_HOME/mongodb-2.0/"

observe_setup_var_lib_dir "$MONGODB_DIR"

. $APP_HOME/.env/OPENSHIFT_NOSQL_DB_HOST
ORIG_DB_HOST=$OPENSHIFT_NOSQL_DB_HOST

. $APP_HOME/.env/OPENSHIFT_INTERNAL_IP
IP=$OPENSHIFT_INTERNAL_IP

if [ "$ORIG_DB_HOST" != "$IP" ]
then
    . $APP_HOME/.env/OPENSHIFT_NOSQL_DB_PASSWORD
    . $APP_HOME/.env/OPENSHIFT_NOSQL_DB_USERNAME

    echo "export OPENSHIFT_NOSQL_DB_HOST='$IP'" > $APP_HOME/.env/OPENSHIFT_NOSQL_DB_HOST
    echo "export OPENSHIFT_NOSQL_DB_URL='mongodb://$OPENSHIFT_NOSQL_DB_USERNAME:$OPENSHIFT_NOSQL_DB_PASSWORD@$IP:27017/'" > $APP_HOME/.env/OPENSHIFT_NOSQL_DB_URL

    sed -i "s,$ORIG_DB_HOST,$IP," $MONGODB_DIR/etc/mongodb.conf
fi

set_app_info "Connection URL: mongodb://$IP:27017/"