#!/bin/bash

# This script defines various utility functions which are useful in the context
# of a Jenkins 'Shell' build task.


# Checks for the presence of the hot_deploy marker in the git repo inside
# the Jenkins workspace. Returns 0 if the marker is present, otherwise 1.
function hot_deploy_marker_present_in_workspace {
	# For some reason, WORKSPACE is set to a relative path, although the Jenkins
  # docs specify it should be absolute. Play it safe by getting the absolute
  # path manually and doing checks relative to our own variable.
	workspace_abs=`cd ~/$WORKSPACE; pwd`
	hot_deploy_file="${workspace_abs}/.openshift/markers/hot_deploy"

	if [ -f $hot_deploy_file ]; then
		return 0
	else
		return 1
	fi
}

# Wraps the remote call to the app start script with a check for the hot
# deployment marker. If the marker is present, the start will be skipped.
#
# Usage: jenkins_start_app <uuid@host>
function jenkins_start_app {
	UPSTREAM_SSH=$1

	if hot_deploy_marker_present_in_workspace; then
  	echo "Skipping application start due to presence of hot_deploy marker"
	else
  	$GIT_SSH $UPSTREAM_SSH 'ctl_all start'
	fi
}

# Wraps the remote call to the app stop script with a check for the hot
# deployment marker. If the marker is present, the stop script will be
# skipped.
#
# Usage: jenkins_stop_app <uuid@host>
function jenkins_stop_app {
	UPSTREAM_SSH=$1

	if hot_deploy_marker_present_in_workspace; then
  	echo "Skipping application stop due to presence of hot_deploy marker"
	else
  	$GIT_SSH $UPSTREAM_SSH 'ctl_all stop'
	fi
}
