#!/bin/bash

# Destroys phpmyadmin instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_phpmyadmin_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

cartridge_type="phpmyadmin-3.4"
source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_embedded_deconfigure "$1" $2 $3
disable_cgroups

PHPMYADMIN_DIR=$(get_cartridge_instance_dir "$cartridge_type")

#
# Stop app
#
run_as_user "${CARTRIDGE_BASE_PATH}/${cartridge_type}/info/bin/app_ctl.sh stop" || warning "Failed to stop ${application}" 121

confirm_pid_gone "${PHPMYADMIN_DIR}/run/httpd.pid"

confirm_log_files_inactive "$PHPMYADMIN_DIR/logs"

#
# Remove environment variables
#
/bin/rm -f $APP_HOME/.env/OPENSHIFT_PHPMYADMIN_*


# Remove phpmyadmin dir. This MUST be after stopping phpmyadmin as the CTL script relies on these.
runcon -l s0-s0:c0.c1023 rm -rf "$PHPMYADMIN_DIR"

#
# Remove ProxyPass definition from apache
#
rm -f /etc/httpd/conf.d/openshift/${uuid}_${namespace}_${application}/${cartridge_type}.conf || warning "Could not remove phpmyadmin apache definition" 156

/usr/sbin/oo-httpd-singular graceful 2> /dev/null || warning "Failed to restart master httpd, please contact support" 120
enable_cgroups
