#!/bin/bash
# Check status of application httpd instance

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Get application status"

    echo "$0 $@" | logger -p local0.notice -t stickshift_httpd_status
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_basic_hook "$1" $2 $3


#
# Get the status of the application
#
if output=$(runuser --shell /bin/sh "$uuid" -c "/usr/bin/wget -qO- http://$(awk '/Listen/{ print $2 }' $APP_DIR/conf.d/stickshift.conf)/server-status?auto" 2>&1)
then
    status_client_result "$output"
else
    client_result "Application '${application}' is either stopped or inaccessible"
fi
send_stopped_status
send_quotas
