#!/bin/bash

# Destroys mongodb instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t stickshift_mongodb_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
CART_INFO_DIR=${CARTRIDGE_BASE_PATH}/embedded/mongodb-2.0/info

app_type="mongodb-2.0"
setup_embedded_deconfigure "$1" $2 $3

source ${CART_INFO_DIR}/lib/util

MONGODB_DIR="$APP_HOME/mongodb-2.0/"

#
# Teardown port proxy (ignore failures or missing hook)
#
( ${CART_INFO_DIR}/hooks/conceal-port "$1" $2 $3 ) &>/dev/null || :

#
# Remove environment variables
#
/bin/rm -f $APP_HOME/.env/OPENSHIFT_NOSQL_DB_USERNAME $APP_HOME/.env/OPENSHIFT_NOSQL_DB_PASSWORD $APP_HOME/.env/OPENSHIFT_NOSQL_DB_TYPE $APP_HOME/.env/OPENSHIFT_NOSQL_DB_HOST $APP_HOME/.env/OPENSHIFT_NOSQL_DB_PORT $APP_HOME/.env/OPENSHIFT_NOSQL_DB_SOCKET $APP_HOME/.env/OPENSHIFT_NOSQL_DB_URL $APP_HOME/.env/OPENSHIFT_NOSQL_DB_CTL_SCRIPT $APP_HOME/.env/OPENSHIFT_NOSQL_DB_MONGODB_20_DUMP $APP_HOME/.env/OPENSHIFT_NOSQL_DB_MONGODB_20_DUMP_CLEANUP $APP_HOME/.env/OPENSHIFT_NOSQL_DB_MONGODB_20_RESTORE $APP_HOME/.env/OPENSHIFT_NOSQL_DB_MONGODB_20_EMBEDDED_TYPE

stop_mongodb

confirm_pid_gone "${MONGODB_DIR}/pid/mongodb.pid"

runcon -l s0-s0:c0.c1023 rm -rf "$MONGODB_DIR" "$MONGODB_DIR/${application}_mongodb_ctl.sh"