#!/bin/bash

# Destroys mongodb instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t stickshift_mongodb_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

cartridge_type="mongodb-2.0"
source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/git
CART_INFO_DIR=${CARTRIDGE_BASE_PATH}/embedded/mongodb-2.0/info

CART_INFO_DIR=${CARTRIDGE_BASE_PATH}/embedded/$cartridge_type/info
setup_embedded_deconfigure "$1" $2 $3
disable_cgroups

source ${CART_INFO_DIR}/lib/util

MONGODB_DIR=$(get_cartridge_instance_dir "$cartridge_type")

source_if_exists "$APP_HOME/.env/OPENSHIFT_GEAR_TYPE"

#
# Teardown port proxy (ignore failures or missing hook)
#
( ${CART_INFO_DIR}/hooks/conceal-port "$1" $2 $3 ) &>/dev/null || :


# For non-embedded (dedicated) mongo gear, destroy the git repo and stop app.
if [ "mongodb-2.0" = "$OPENSHIFT_GEAR_TYPE" ]; then
   $CART_INFO_DIR/hooks/conceal-port "$application" "$namespace" "$uuid"

   # Destroy git repo and stop app.
   destroy_git_repo $application $uuid

   enable_stale_detection

   stop_app
fi


stop_mongodb

confirm_pid_gone "${MONGODB_DIR}/pid/mongodb.pid"

#
# Remove environment variables
#
/bin/rm -f $APP_HOME/.env/OPENSHIFT_NOSQL_DB_USERNAME $APP_HOME/.env/OPENSHIFT_NOSQL_DB_PASSWORD $APP_HOME/.env/OPENSHIFT_NOSQL_DB_TYPE $APP_HOME/.env/OPENSHIFT_NOSQL_DB_HOST $APP_HOME/.env/OPENSHIFT_NOSQL_DB_PORT $APP_HOME/.env/OPENSHIFT_NOSQL_DB_SOCKET $APP_HOME/.env/OPENSHIFT_NOSQL_DB_URL $APP_HOME/.env/OPENSHIFT_NOSQL_DB_CTL_SCRIPT $APP_HOME/.env/OPENSHIFT_NOSQL_DB_MONGODB_20_DUMP $APP_HOME/.env/OPENSHIFT_NOSQL_DB_MONGODB_20_DUMP_CLEANUP $APP_HOME/.env/OPENSHIFT_NOSQL_DB_MONGODB_20_RESTORE $APP_HOME/.env/OPENSHIFT_NOSQL_DB_MONGODB_20_EMBEDDED_TYPE

runcon -l s0-s0:c0.c1023 rm -rf "$MONGODB_DIR" "$MONGODB_DIR/${application}_mongodb_ctl.sh"

# For non-embedded (dedicated) mongo gear, destroy the gear.
if [ "mongodb-2.0" = "$OPENSHIFT_GEAR_TYPE" ]; then
    # Blow away the directories.
    rm_app_dir

    # Remove apache vhost configuration.
    rm_httpd_proxy $uuid $namespace $application
fi
enable_cgroups
