#!/bin/bash -e

cartridge_type="mongodb-2.0"
gear_type=$cartridge_type

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
CART_INFO_DIR=${CARTRIDGE_BASE_PATH}/embedded/$cartridge_type/info

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3

setup_basic_vars

if [ ! -d "$GEAR_BASE_DIR/$3/$1" ]; then
    #  This gear is dedicated to running mongo - configure it as such.
    unobfuscate_app_home $uuid $namespace $application
fi
