#!/bin/bash

# Restarts application's embedded MongoDB instance
CART_NAME=mongodb
CART_VERSION=2.0

# Exit on any errors
set -e

MONGODB_DIR="$APP_HOME/mongodb-2.0/"

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Get application status"

    echo "$0 $@" | logger -p local0.notice -t stickshift_mongodb_restart
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_basic_hook "$1" $2 $3

MONGODB_DIR="$APP_HOME/$CART_NAME-$CART_VERSION/"
mongodbctl="$MONGODB_DIR/${application}_mongodb_ctl.sh"

CART_INFO_DIR="${CARTRIDGE_BASE_PATH}/embedded/$CART_NAME-$CART_VERSION/info"
source ${CART_INFO_DIR}/lib/util

#
# Restart application
#
rm -f "$MONGODB_DIR/run/stop_lock"
restart_mongodb
zstatus=$(runuser --shell /bin/sh "$uuid" "$mongodbctl" status 2>&1)
[[ "$zstatus" == *running ]]  &&  exit 0
repair_mongodb