#!/bin/bash

# Destroys jenkins instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_jenkins_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

cartridge_type="jenkins-1.4"
source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_deconfigure "$1" $2 $3


$CART_INFO_DIR/hooks/conceal-port "$application" "$namespace" "$uuid"

if [ ! -d "$APP_HOME/app-root" ]
then
    echo "${application}.  Application directory doesn't exist:  $APP_HOME/app-root"
else

    disable_cgroups

    #
    # Import env vars so they can be used:
    #
    import_env_vars

    destroy_git_repo $application $uuid

    jenkins_pid=`pgrep -U $uid -f ".*java.*-jar.*jenkins.war.*--httpListenAddress=${OPENSHIFT_JENKINS_IP}.*" 2> /dev/null`

    stop_app

    force_kill $jenkins_pid

    rm_cartridge_instance_dir "$cartridge_type"

    enable_cgroups
fi


#
# Remove virtualhost definition for apache
#
rm_httpd_proxy $uuid $namespace $application

$CART_INFO_DIR/hooks/pre-destroy "$@"
