#!/bin/bash

# Destroys jbossas-7 instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t stickshift_jboss_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_deconfigure "$1" $2 $3

remove_all_proxy_ports $uuid

M2_DIR="$APP_HOME/.m2" # maven dir
JAVA_PREFS_DIR="$APP_HOME/.java" # Java preferences dir

destroy_git_repo $application $uuid

stop_app

confirm_pid_gone "${APP_DIR}/run/jboss.pid"

rm_app_dir

rm_unobfuscated_app_home $namespace $application

# remove the Maven repository.
runcon -l s0-s0:c0.c1023 rm -rf "$M2_DIR"

# remove the Java preferences dir
runcon -l s0-s0:c0.c1023 rm -rf "$JAVA_PREFS_DIR"

#
# Remove virtualhost definition for apache
#
rm_httpd_proxy $uuid $namespace $application
