#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH
source ${OPENSHIFT_PHP_DIR}usr/lib/php_context

export ERB_PHP_INI_SCAN_DIR=$OPENSHIFT_PHP_DIR/usr/${OPENSHIFT_PHP_VERSION}/etc/php.d

function system_php_dir {
    local phpscl=$(expr "$(php_context 'echo $X_SCLS')" : '.*\(php[^ ]\+\).*')
    [ -n "${phpscl}" ] && echo "/opt/rh/${phpscl}/root/etc/php.d" \
        || echo "/etc/php.d"
}

function scan_for_php_modules {
    local testcmd=""

    for inifile in ${ERB_PHP_INI_SCAN_DIR}/*.ini
    do
        inifile=${inifile##*/}
        local module=${inifile%.ini}
        local modvar="OPENSHIFT_PHP_${module^^}_ENABLED"
        testcmd+="@dl('${module}.so') and printf('${modvar} '); "
    done
    for inifile in $(system_php_dir)/*.ini
    do
        inifile=${inifile##*/}
        local module=${inifile%.ini}
        if ! [ -e ${ERB_PHP_INI_SCAN_DIR}/${module}.ini \
                  -o -e ${ERB_PHP_INI_SCAN_DIR}/${module}.ini.erb ]
        then
            local modvar="OPENSHIFT_PHP_${module^^}_ENABLED"
            testcmd+="@dl('${module}.so') and printf('${modvar} '); "
        fi
    done

    for modvar in $(php_context "php -n -r \"${testcmd}\"" 2>/dev/null)
    do
        echo 'true' > ${OPENSHIFT_PHP_DIR}env/${modvar}
    done
}

function copy_inifile {
    local modvar="$1"
    local srcdir="$2"

    local modvar_val=`cat ${OPENSHIFT_PHP_DIR}env/${modvar}`

    if [[ "${modvar_val}" == "true" ]]
    then
        if [[ -e ${srcdir}/${inifile} ]]
        then
            cat ${srcdir}/${inifile} >> ${PHP_MODULES_INI}
        fi
    fi
}

function enable_modules {
    export PHP_MODULES_INI=${OPENSHIFT_PHP_DIR}configuration/etc/php.d/openshift.ini
    export ERB_PHPRC=$OPENSHIFT_PHP_DIR/usr/shared/etc/php.ini.erb

    local SYSTEM_PHP_D_DIR=$(system_php_dir)

    oo-erb ${ERB_PHPRC} > ${PHPRC}
    oo-erb ${ERB_PHP_INI_SCAN_DIR}/apc.ini.erb > ${PHP_INI_SCAN_DIR}/apc.ini
    oo-erb ${ERB_PHP_INI_SCAN_DIR}/xdebug.ini.erb > ${PHP_INI_SCAN_DIR}/xdebug.ini

    echo > ${PHP_MODULES_INI}
    for inifile in ${ERB_PHP_INI_SCAN_DIR}/*.ini
    do
        inifile=${inifile##*/}
        local module=${inifile%.ini}
        local modvar="OPENSHIFT_PHP_${module^^}_ENABLED"
        copy_inifile "${modvar}" "${ERB_PHP_INI_SCAN_DIR}"
    done
    for inifile in ${SYSTEM_PHP_D_DIR}/*.ini
    do
        inifile=${inifile##*/}
        if [[ -e ${ERB_PHP_INI_SCAN_DIR}/${inifile} || -e ${ERB_PHP_INI_SCAN_DIR}/${inifile}.erb ]]
        then
            continue
        fi
        local module=${inifile%.ini}
        local modvar="OPENSHIFT_PHP_${module^^}_ENABLED"
        copy_inifile "${modvar}" "${SYSTEM_PHP_D_DIR}"
    done
}