#!/bin/bash

source ${OPENSHIFT_PHP_DIR}usr/lib/php_context

function system_php_dir {
    local phpscl=$(expr "$(php_context 'echo $X_SCLS')" : '.*\(php[^ ]\+\).*')
    [ -n "${phpscl}" ] && echo "/opt/rh/${phpscl}/root/etc/php.d" \
        || echo "/etc/php.d"
}

function scan_for_php_modules {
    local php_ident=(${OPENSHIFT_PHP_IDENT//:/ })
    # php_context function(s) need this var:
    local OPENSHIFT_PHP_VERSION=${OPENSHIFT_PHP_VERSION-${php_ident[2]}}
    local usr_php_ini_dir=$OPENSHIFT_PHP_DIR/usr/${OPENSHIFT_PHP_VERSION}/etc/php.d
    local testcmd=""

    for inifile in ${usr_php_ini_dir}/*.ini
    do
        inifile=${inifile##*/}
        local module=${inifile%.ini}
        local modvar="OPENSHIFT_PHP_${module^^}_ENABLED"
        testcmd+="@dl('${module}.so') and printf('${modvar} '); "
    done
    for inifile in $(system_php_dir)/*.ini
    do
        inifile=${inifile##*/}
        local module=${inifile%.ini}
        if ! [ -e ${usr_php_ini_dir}/${module}.ini \
                  -o -e ${usr_php_ini_dir}/${module}.ini.erb ]
        then
            local modvar="OPENSHIFT_PHP_${module^^}_ENABLED"
            testcmd+="@dl('${module}.so') and printf('${modvar} '); "
        fi
    done
    for modvar in $(php_context "php -n -r \"${testcmd}\"" 2>/dev/null)
    do
        echo 'true' > ${OPENSHIFT_PHP_DIR}env/${modvar}
    done
}
