#!/bin/bash

# Import Environment Variables
for f in ~/.env/*
do
    . $f
done

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

CART_NAME=$(get_cartridge_name_from_path)
CART_NS=$(get_cartridge_namespace_from_path)
CART_DIR=$(get_env_var_dynamic "OPENSHIFT_${CART_NS}_CART_DIR")
JBOSS_DIR=${CART_DIR}/${CART_NAME}

# Clean up logs
for logdir in `awk 'BEGIN {
                           for (a in ENVIRON)
                           if (a ~ /LOG_DIR$/)
                           print ENVIRON[a] }'`
do
    client_message "Emptying log dir: ${logdir}"
    rm -rf ${logdir}* ${logdir}.[^.]*
done


standalone_tmp=${JBOSS_DIR}/standalone/tmp/
if [ -d $standalone_tmp ]
then
    client_message "Emptying tmp dir: $standalone_tmp"
    rm -rf $standalone_tmp/* $standalone_tmp/.[^.]*
fi
