#!/bin/bash
#
# Destroys a Node instance (Node.js Application).
#

# Variables.
source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

function print_help() {
   echo "Usage: $0 app-name namespace uuid"
   echo "$0 $@" | logger -p local0.notice -t stickshift_nodejs_deconfigure
   exit 1
}


#
# main():
#

# Parse arguments.
while getopts 'd' OPTION; do
   case $OPTION in
      d)  set -x      ;;
      ?)  print_help  ;;
   esac
done

# Ensure arguments.
[ $# -eq 3 ] || print_help

# Source in common utility functions.
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

# Deconfigure app.
setup_deconfigure "$1" $2 $3

remove_all_proxy_ports $uuid

# Destroy git repo and stop app.
destroy_git_repo $application $uuid
stop_app

# Confirm stop + no activity in logs.
confirm_pid_gone "${APP_DIR}/run/nodejs.pid"
confirm_log_files_inactive "$APP_DIR/logs"

# Blow away the directories.
rm_app_dir
rm_unobfuscated_app_home $namespace $application

# And finally, remove virtualhost definition added to Apache.
rm_httpd_proxy $uuid $namespace $application
