#!/bin/bash

# Control a scalable application's haproxy cartridge instance

# Exit on any errors
set -e

CARTRIDGE_NAME="haproxy"
CARTRIDGE_VERSION="1.4"
export CARTRIDGE_TYPE="$CARTRIDGE_NAME-$CARTRIDGE_VERSION"


function print_help {
    cmd=$(basename "$0")
    echo "Usage: $0 app-name namespace uuid"
    echo "$cmd scalable application's haproxy service"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_haproxy_$cmd
    exit 1
}


while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
HAPROXY_CTL_SH="${CARTRIDGE_BASE_PATH}/${CARTRIDGE_TYPE}/info/bin/app_ctl.sh"

setup_basic_hook "$1" $2 $3

hook_name=$(basename "$0")
run_as_user "${HAPROXY_CTL_SH} $hook_name"

