#!/bin/bash

# Deploy httpd proxy

# Exit on any errors
set -e

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/apache
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/network

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Deploy httpd proxy for an application"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_deploy_httpd_proxy
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3

APP_HOME="${GEAR_BASE_DIR}/$uuid"

CART_INFO_DIR=${CARTRIDGE_BASE_PATH}/haproxy-1.4/info

. $APP_HOME/.env/OPENSHIFT_HAPROXY_STATUS_IP

#
# Create virtualhost definition for apache
#
${CART_INFO_DIR}/bin/deploy_httpd_proxy.sh $application $namespace $uuid $OPENSHIFT_HAPROXY_STATUS_IP

