#!/bin/bash

# Confirms all required ruby bits are in place or fails

set -e

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

[ -z "$CARTRIDGE_DIR" ] && CARTRIDGE_DIR="${CARTRIDGE_BASE_PATH}/ruby-1.9/"

function print_help {
    echo "Usage: uuid"
    exit 1
}

function quit {
    echo -e "$1" 1>&2
    exit 5
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 1 ] || print_help

uuid=$1

pkglist="ruby193 ruby193-ruby ruby193-ruby-libs ruby193-ruby-irb  \
         ruby193-rubygems ruby193-rubygem-rack mod_passenger httpd"
# FIXME: Passenger bits are not yet available in the ruby193 repo.
#pkglist="$pkglist ruby193-rubygem-passenger ruby193-rubygem-passenger-native \
#          ruby193-rubygem-passenger-native-libs 
rpm -q $pkglist > /dev/null || quit "Missing packages"


[ -d "$CARTRIDGE_DIR" ] || quit "Missing cartridge dir: $CARTRIDGE_DIR"
