#!/usr/bin/env oo-ruby

require 'rubygems'
require 'daemons'

raise 'Watchman must run as root' if Process.euid != 0

options = {
    app_name:   'watchman',
    backtrace:  true,
    ontop:      false,
    log_output: true,
    dir_mode:   :system,
    log_dir:    '/var/log/openshift/node',
    multiple:   false,
}

Daemons.run('/usr/sbin/oo-watchman', options)