#!/bin/bash

# Destroys perl instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_perl_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

cartridge_type="perl-5.10"
source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_deconfigure "$1" $2 $3

PERLCART_INSTANCE_DIR=$(get_cartridge_instance_dir "$cartridge_type")

source $APP_HOME/.env/OPENSHIFT_APP_UUID
container_uuid=$3
/usr/bin/oo-delete-endpoints --with-app-uuid $OPENSHIFT_APP_UUID --with-container-uuid $container_uuid --cart-name $cartridge_type

if [ ! -d "$APP_HOME/app-root" ]
then
    echo "${application}.  Application directory doesn't exist:  $APP_HOME/app-root"
else

    disable_cgroups

    destroy_git_repo $application $uuid

    stop_app

    confirm_pid_gone "${PERLCART_INSTANCE_DIR}/run/httpd.pid"

    confirm_log_files_inactive "$PERLCART_INSTANCE_DIR/logs"

    rm_cartridge_instance_dir "$cartridge_type"
    
    enable_cgroups
fi


#
# Remove virtualhost definition for apache
#
rm_httpd_proxy $uuid $namespace $application

