#!/bin/bash
echo "Importing cartridges from disk..."
find /var/www/openshift/docker -iname manifest.yml | oo-admin-ctl-cartridge -c import --activate
echo "Adding the default node..."
oo-admin-ctl-node -c create -n node1 -i 172.17.42.1:43273