# Represents an autogenerated SSH key used by a component in the applicaiton to access other application gears.
# See {Application#process_commands}
# @!attribute [r] name
#   @return [String] Name of the ssh key. Must be unique for the application
# @!attribute [r] type
#   @return [String] Type of the ssh key. Must be "ssh-rsa" or "ssh-dsa"  
# @!attribute [r] content
#   @return [String] SSH key content.
class ApplicationSshKey
  include Mongoid::Document
  embedded_in :application, class_name: Application.name
  field :name, :type => String
  field :type, :type => String, :default => "ssh-rsa"
  field :content, :type => String
  
  validates :name, :presence => true, :format => /\A[A-Za-z0-9]+\z/, :length => { :maximum => 256, :minimum => 1 }
  validates :type, :presence => true, :format => /\A(ssh-rsa|ssh-dss)\z/
  validates :content, :presence => true, :format => /\A[A-Za-z0-9\+\/=]+\z/  
end
