# Class representing an autogenerated {Domain} level ssh key.
# This key is used by applications like Jenkins that need to operate on other applications within the same domain.
# @!attribute [r] domain
#   @return [Domain] The domain that owns this key.
# @!attribute [r] name
#   @return [String] Name of the ssh key. Must be unique for the domain.
# @!attribute [r] type
#   @return [String] Type of the ssh key. Must be "ssh-rsa" or "ssh-dsa".
# @!attribute [r] content
#   @return [String] SSH key content
class SystemSshKey
  include Mongoid::Document
  embedded_in :domain, class_name: Domain.name
  field :name, :type => String
  field :type, :type => String, :default => "ssh-rsa"
  field :content, :type => String
  
  validates :name, :presence => true, :format => /\A[A-Za-z0-9]+\z/, :length => { :maximum => 256, :minimum => 1 }
  validates :type, :presence => true, :format => /\A(ssh-rsa|ssh-dss)\z/
  validates :content, :presence => true, :format => /\A[A-Za-z0-9\+\/=]+\z/  
end
