#!/bin/bash

# Destroys rockmongo instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t stickshift_10gen_mms_agent_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

app_type="10gen-mms-agent-0.1"
setup_embedded_deconfigure "$1" $2 $3

MMS_DIR=`echo $APP_HOME/10gen-mms-agent-0.1 | tr -s /` # ensure that there aren't double /'s
MMS_CTL_SCRIPT="$MMS_DIR/${application}_10gen_mms_agent_ctl.sh"
APP_DIR=`echo $APP_HOME/${application} | tr -s /` # ensure that there aren't double /'s

#
# Stop app
#
run_as_user "$MMS_CTL_SCRIPT stop" || warning "Failed to stop ${application}" 121

confirm_pid_gone "${MMS_DIR}/run/mms-agent.pid"
confirm_log_files_inactive "$MMS_DIR/logs"

#
# Remove environment variables
#
/bin/rm -f $APP_HOME/.env/OPENSHIFT_10GEN_MMS_AGENT_GEAR_DIR $APP_HOME/.env/OPENSHIFT_10GEN_MMS_AGENT_CTL_SCRIPT 


# Remove 10gen mms agent dir. This MUST be after stopping the agent as the CTL script relies on these.
runcon -l s0-s0:c0.c1023 rm -rf "$MMS_DIR"
runcon -l s0-s0:c0.c1023 rm -rf "$APP_DIR/.openshift"