#!/bin/bash

# Destroys jenkins instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t stickshift_jenkins_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_deconfigure "$1" $2 $3

remove_all_proxy_ports $uuid

#
# Import env vars so they can be used:
#
import_env_vars

destroy_git_repo $application $uuid

jenkins_pid=`pgrep -U $uid -f ".*java.*-jar.*jenkins.war.*--httpListenAddress=${OPENSHIFT_INTERNAL_IP}.*" 2> /dev/null`

stop_app

force_kill $jenkins_pid

rm_app_dir

remove_ssh_key

rm_unobfuscated_app_home $namespace $application

#
# Remove virtualhost definition for apache
#
rm_httpd_proxy $uuid $namespace $application

client_result "Successfully destroyed application: $application"

remove_env_var "JENKINS_URL"
remove_env_var "JENKINS_USERNAME"
remove_env_var "JENKINS_PASSWORD"
