#!/bin/bash

[ ! -z "$LI_CONTROLLER_LIB_APACHE" ] && return 0
LI_CONTROLLER_LIB_APACHE=true

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

function rm_httpd_proxy {
    uuid=$1
    namespace="$2"
    application=$3
    rm -rf /etc/httpd/conf.d/stickshift/${uuid}_${namespace}_${application}.conf /etc/httpd/conf.d/stickshift/${uuid}_${namespace}_${application} || echo "Could not remove apache definition" 1>&2
    /sbin/service httpd configtest 2> /dev/null && /sbin/service httpd graceful || echo "Failed to restart master httpd, please contact support" 1>&2
}

function restart_httpd_graceful {
    /sbin/service httpd configtest 2> /dev/null && /sbin/service httpd graceful || error "Failed to restart master httpd, please contact support" 120
}
