#!/bin/bash

# Removes the batch processing service (cron) support from the application.

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t stickshift_cron_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

cartridge_type="cron-1.4"
source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_embedded_deconfigure "$1" $2 $3
disable_cgroups


source ${CART_INFO_DIR}/lib/util

CRON_INSTANCE_DIR=$(get_cartridge_instance_dir "$cartridge_type")

disable_cronjobs

#
# Remove environment variables
#
[ -f $APP_HOME/.env/OPENSHIFT_BATCH_TYPE ]  &&  source $APP_HOME/.env/OPENSHIFT_BATCH_TYPE
if [ "$OPENSHIFT_BATCH_TYPE" = "cron" ]; then
   /bin/rm -f $APP_HOME/.env/OPENSHIFT_BATCH_TYPE $APP_HOME/.env/OPENSHIFT_BATCH_CTL_SCRIPT $APP_HOME/.env/OPENSHIFT_BATCH_CRON_14_EMBEDDED_TYPE
fi

runcon -l s0-s0:c0.c1023 rm -rf "$CRON_INSTANCE_DIR" "$CRON_INSTANCE_DIR/${application}_cron_ctl.sh"
enable_cgroups

