#!/bin/bash

# Publishes the mongodb database connection information.

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Publish mongodb database connection information"

    echo "$0 $@" | logger -p local0.notice -t stickshift_mongodb_publish_conn_info
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source /etc/stickshift/stickshift-node.conf
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_configure "$1" $2 $3

import_env_vars

# Check scalability and setup entries accordingly.
if is_a_scalable_app; then
    mongodb_host=$OPENSHIFT_GEAR_DNS
    mongodb_port=$OPENSHIFT_NOSQL_DB_PROXY_PORT
    mongodb_dburl="$OPENSHIFT_NOSQL_DB_TYPE://$OPENSHIFT_NOSQL_DB_USERNAME:$OPENSHIFT_NOSQL_DB_PASSWORD@$mongodb_host:$mongodb_port/"
    mongodb_dbsocket=""
    echo -n "OPENSHIFT_NOSQL_DB_GEAR_UUID=$OPENSHIFT_GEAR_UUID; "
    echo -n "OPENSHIFT_NOSQL_DB_GEAR_DNS=$OPENSHIFT_GEAR_DNS; "
    echo -n "OPENSHIFT_NOSQL_DB_CTL_ONGEAR_SCRIPT=$OPENSHIFT_NOSQL_DB_CTL_SCRIPT; "
fi

echo -n "OPENSHIFT_NOSQL_DB_TYPE=$OPENSHIFT_NOSQL_DB_TYPE; "
echo -n "OPENSHIFT_NOSQL_DB_USERNAME=$OPENSHIFT_NOSQL_DB_USERNAME; "
echo -n "OPENSHIFT_NOSQL_DB_PASSWORD=$OPENSHIFT_NOSQL_DB_PASSWORD; "
echo -n "OPENSHIFT_NOSQL_DB_HOST=$OPENSHIFT_NOSQL_DB_HOST; "
echo -n "OPENSHIFT_NOSQL_DB_PORT=${mongodb_port:-$OPENSHIFT_NOSQL_DB_PORT}; "
echo -n "OPENSHIFT_NOSQL_DB_URL=${mongodb_dburl:-$OPENSHIFT_NOSQL_DB_URL}; "
echo -n "OPENSHIFT_NOSQL_DB_SOCKET=${mongodb_dbsocket:-$OPENSHIFT_NOSQL_DB_SOCKET}; "
echo -n "OPENSHIFT_NOSQL_DB_MONGODB_20_DUMP=$OPENSHIFT_NOSQL_DB_MONGODB_20_DUMP; "
echo -n "OPENSHIFT_NOSQL_DB_MONGODB_20_DUMP_CLEANUP=$OPENSHIFT_NOSQL_DB_MONGODB_20_DUMP_CLEANUP; "
echo -n "OPENSHIFT_NOSQL_DB_MONGODB_20_EMBEDDED_TYPE=$OPENSHIFT_NOSQL_DB_MONGODB_20_EMBEDDED_TYPE; "
echo -n "OPENSHIFT_NOSQL_DB_MONGODB_20_RESTORE=$OPENSHIFT_NOSQL_DB_MONGODB_20_RESTORE; "
echo ""

