#!/bin/bash

# We are kind of abusing string evaluation of equality, so set LANG for the
# specific check for version
orig_lang=$LANG
export LANG=C

ruby_ver=$(rpm -q ruby --qf "%{version}")
if [[ $ruby_ver < "1.9" ]]; then
    # Ensure that the ruby193 SCL's directories come first in the PATH,
    # LD_LIBRARY_PATH, PKG_CONFIG_PATH, and MANPATH variables.

    export LANG=$orig_lang
    dir=/opt/rh/ruby193/root/usr/bin
    [[ ${PATH}: =~ ^$dir: ]] || export PATH="$dir:${PATH/:$dir}"
    dir=/opt/rh/ruby193/root/usr/lib64:/opt/rh/v8314/root/usr/lib64
    [[ ${LD_LIBRARY_PATH}: =~ ^$dir: ]] || export LD_LIBRARY_PATH="$dir:${LD_LIBRARY_PATH/:$dir}"

    exec "$@"

    # We use the above implementation instead of the following because we want to
    # avoid using the scl command.
    #
    # scl <action> <collection1>...<collectionN> <command> doesn't handle multiple params for command.
    # If it did we would use:  exec scl enable ruby193 "$@"
    #COMMAND="$(printf "%q " "$@")"
    #exec scl enable ruby193 "$COMMAND"
else
    export LANG=$orig_lang
    exec "$@"
fi
