#!/bin/bash

# Removes embedded switchyard from an JBoss instance

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_jenkins_client_configure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

cartridge_type="switchyard-0.6"
source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_embedded_deconfigure "$1" $2 $3

module_path="OPENSHIFT_JBOSSAS_MODULE_PATH"
if [ -f "$APP_HOME/.env/OPENSHIFT_JBOSSEAP_CLUSTER" ]
then
  module_path="OPENSHIFT_JBOSSEAP_MODULE_PATH"
fi

if [ -f "$APP_HOME/.env/$module_path" ]
then
     sed -i 's/:\/etc\/alternatives\/switchyard-0.6\/modules//g' $APP_HOME/.env/$module_path
     sed -i 's/\/etc\/alternatives\/switchyard-0.6\/modules://g' $APP_HOME/.env/$module_path
     sed -i 's/\/etc\/alternatives\/switchyard-0.6\/modules//g' $APP_HOME/.env/$module_path
     
     if grep -q "''" "$APP_HOME/.env/$module_path"; then
     	rm -f $APP_HOME/.env/$module_path
     fi
fi

#if [ -f "$APP_HOME/.env/OPENSHIFT_JBOSSEAP_CLUSTER" ]
#then
#	java  -jar ${CARTRIDGE_BASE_PATH}/embedded/switchyard-0.6/info/configuration/saxon9he.jar \
#		${APP_HOME}/app-root/runtime/repo/.openshift/config/standalone.xml \
#		${CARTRIDGE_BASE_PATH}/embedded/switchyard-0.6/info/configuration/undo_standalone_eap6.0.0.xsl > ${APP_HOME}/app-root/runtime/repo/.openshift/config/standalone.xml.new
#		mv ${APP_HOME}/app-root/runtime/repo/.openshift/config/standalone.xml.new ${APP_HOME}/app-root/runtime/repo/.openshift/config/standalone.xml
#fi

#if [ -f "$APP_HOME/.env/OPENSHIFT_JBOSSAS_CLUSTER" ]
#then
#    java  -jar ${CARTRIDGE_BASE_PATH}/embedded/switchyard-0.6/info/configuration/saxon9he.jar \
#		${APP_HOME}/app-root/runtime/repo/.openshift/config/standalone.xml \
#		${CARTRIDGE_BASE_PATH}/embedded/switchyard-0.6/info/configuration/undo_standalone_as7.1.0.xsl > ${APP_HOME}/app-root/runtime/repo/.openshift/config/standalone.xml.new
#		mv ${APP_HOME}/app-root/runtime/repo/.openshift/config/standalone.xml.new ${APP_HOME}/app-root/runtime/repo/.openshift/config/standalone.xml
#fi


client_result ""
client_result "SwitchYard 0.6 removed."
client_result ""
