#!/bin/bash

# Removes embedded switchyard from an AS7 instance

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_jenkins_client_configure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

cartridge_type="switchyard-0.6"
source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_embedded_deconfigure "$1" $2 $3

#
# Create the core of the application
#

if [ -f "$APP_HOME/.env/OPENSHIFT_JBOSSAS_MODULE_PATH" ]
then
     sed -i 's/:\/etc\/alternatives\/switchyard-0.6\/modules//g' $APP_HOME/.env/OPENSHIFT_JBOSSAS_MODULE_PATH
     sed -i 's/\/etc\/alternatives\/switchyard-0.6\/modules://g' $APP_HOME/.env/OPENSHIFT_JBOSSAS_MODULE_PATH
     sed -i 's/\/etc\/alternatives\/switchyard-0.6\/modules//g' $APP_HOME/.env/OPENSHIFT_JBOSSAS_MODULE_PATH
     
     if grep -q "''" "$APP_HOME/.env/OPENSHIFT_JBOSSAS_MODULE_PATH"; then
     	rm -f $APP_HOME/.env/OPENSHIFT_JBOSSAS_MODULE_PATH
     fi
fi

client_result ""
client_result "SwitchYard 0.6 removed."
client_result ""
