#!/bin/bash

# Gets status of instance

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Get application status"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_mysql_status
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_basic_hook "$1" $2 $3

#
# Get the status of the application
#

module_path="OPENSHIFT_JBOSSAS_MODULE_PATH"
if [ -f "$APP_HOME/.env/OPENSHIFT_JBOSSEAP_CLUSTER" ]
then
  module_path="OPENSHIFT_JBOSSEAP_MODULE_PATH"
fi

source $APP_HOME/.env/$module_path

client_result "SwitchYard modules are enabled at module_path=/etc/alternatives/switchyard-0.6/modules"
