#!/bin/bash

# Deploy httpd proxy

# Exit on any errors
set -e

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/apache
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/network

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Deploy httpd proxy for an application"

    echo "$0 $@" | logger -p local0.notice -t stickshift_deploy_httpd_proxy
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3

APP_HOME="$GEAR_BASE_DIR/$uuid"

. $APP_HOME/.env/OPENSHIFT_GEAR_TYPE

CART_INFO_DIR=$CARTRIDGE_BASE_PATH/$OPENSHIFT_GEAR_TYPE/info

. $APP_HOME/.env/OPENSHIFT_INTERNAL_IP

idle=false
HTTP_DIR=`dirname "/etc/httpd/conf.d/stickshift/${uuid}"*/00000_default.conf`
if [ -f $HTTP_DIR/0000000000000_disabled.conf ]
then
  idle=true
fi

#
# Create virtualhost definition for apache
#
export CART_INFO_DIR
if [ -f $CART_INFO_DIR/bin/deploy_httpd_proxy.sh ]
then
  $CART_INFO_DIR/bin/deploy_httpd_proxy.sh $application $namespace $uuid $OPENSHIFT_INTERNAL_IP
else
  $CARTRIDGE_BASE_PATH/abstract/info/bin/deploy_httpd_proxy.sh $application $namespace $uuid $OPENSHIFT_INTERNAL_IP
fi

if $idle
then
  rhc-idler -u $uuid
fi

restart_httpd_graceful
