#!/bin/bash

# Start the application httpd instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Start a running application"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_mongodb_conceal_port
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_configure "$1" $2 $3

import_env_vars

rm -f $APP_HOME/.env/OPENSHIFT_MONGODB_DB_PROXY_PORT
proxy_port=$(remove_proxy_port $uuid "$OPENSHIFT_MONGODB_DB_HOST:$OPENSHIFT_MONGODB_DB_PORT")
ret=$?
if [ $ret -ne 0 ]; then
  client_internal_error "$proxy_port"
  exit $ret
fi
exit 0
