#!/bin/bash

# Publishes the mongodb database connection information.

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Publish mongodb database connection information"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_mongodb_publish_conn_info
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source /etc/openshift/node.conf
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util


for v in "OPENSHIFT_MONGODB_DB_GEAR_DNS" "OPENSHIFT_MONGODB_DB_GEAR_UUID" "OPENSHIFT_MONGODB_DB_HOST" \
         "OPENSHIFT_MONGODB_DB_PASSWORD" "OPENSHIFT_MONGODB_DB_PORT"      "OPENSHIFT_MONGODB_DB_URL" \
         "OPENSHIFT_MONGODB_DB_USERNAME";
do
    app_remove_env_var $v
done
