#!/bin/bash

# Restarts application's embedded MongoDB instance
CART_NAME=mongodb
CART_VERSION=2.2
cartridge_type="mongodb-2.2"

# Exit on any errors
set -e

MONGODB_DIR="$APP_HOME/mongodb-2.2/"

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Get application status"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_mongodb_restart
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_basic_hook "$1" $2 $3

MONGODB_DIR="$APP_HOME/$cartridge_type/"

CART_INFO_DIR="${CARTRIDGE_BASE_PATH}/embedded/$cartridge_type/info"
source ${CART_INFO_DIR}/lib/util

mongodb_ctl="${CARTRIDGE_BASE_PATH}/$cartridge_type/info/bin/mongodb_ctl.sh"

#
# Restart application
#
rm -f "$MONGODB_DIR/run/stop_lock"
restart_database
zstatus=$(runuser --shell /bin/sh "$uuid" "$mongodb_ctl" status 2>&1)
[[ "$zstatus" == *running ]]  &&  exit 0
repair_mongodb
