#!/bin/bash

# Starts application's embedded MongoDB instance
CART_NAME=mongodb
CART_VERSION=2.2
cartridge_type="mongodb-2.2"

# Exit on any errors
set -e


function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Start a running application"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_mongodb_start
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_basic_hook "$1" $2 $3

MONGODB_DIR="$APP_HOME/$cartridge_type/"

CART_INFO_DIR="${CARTRIDGE_BASE_PATH}/embedded/$cartridge_type/info"
source $CART_INFO_DIR/lib/util

#
# Start application
#
rm -f "$MONGODB_DIR/run/stop_lock"
start_database
