#!/bin/bash

# Gets status of instance

# Exit on any errors
set -e

cartridge_type="mongodb-2.2"

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Get application status"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_mongodb_status
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_basic_hook "$1" $2 $3

MONGODB_DIR="$APP_HOME/$cartridge_type/"
mongodb_ctl="${CARTRIDGE_BASE_PATH}/$cartridge_type/info/bin/mongodb_ctl.sh"

#
# Get the status of the application
#

if output=$(runuser --shell /bin/sh "$uuid" "$mongodb_ctl" status 2>&1)
then
    status_client_result "$output"
else
    client_result "MongoDB is either stopped or inaccessible"
fi
