#!/bin/bash

# Destroys mysql instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_mysql_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

cartridge_type="mysql-5.1"
source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/git

setup_embedded_deconfigure "$1" $2 $3
disable_cgroups

CART_INFO_DIR=${CARTRIDGE_BASE_PATH}/embedded/$cartridge_type/info
source ${CART_INFO_DIR}/lib/util

MYSQL_DIR=$(get_cartridge_instance_dir "$cartridge_type")

# cartridge already removed
if [ ! -d "$MYSQL_DIR" ]; then
  exit 0
fi

source $APP_HOME/.env/OPENSHIFT_APP_UUID
container_uuid=$3
/usr/bin/oo-delete-endpoints --with-app-uuid $OPENSHIFT_APP_UUID --with-container-uuid $container_uuid --cart-name $cartridge_type

# For non-embedded (dedicated) mysql gear, destroy the git repo and stop app.
if only_cart_on_gear $cartridge_type; then
   enable_stale_detection

   stop_app
fi

stop_database
confirm_pid_gone "${MYSQL_DIR}/pid/mysql.pid"

#
# Remove environment variables
#
/bin/rm -f $APP_HOME/.env/OPENSHIFT_MYSQL_DB*

# Remove deprecated env vars
if [ -f $APP_HOME/.env/TYPELESS_TRANSLATED_VARS ]; then
    sed -i '/OPENSHIFT_DB_*/d' $APP_HOME/.env/TYPELESS_TRANSLATED_VARS
fi

# For non-embedded (dedicated) mysql gear, destroy the gear.
if only_cart_on_gear $cartridge_type; then
    # Remove apache vhost configuration.
    rm_httpd_proxy $uuid $namespace $application
fi

rm_cartridge_instance_dir "$cartridge_type"
enable_cgroups
