#!/bin/bash

# Publishes the mysql database connection information.

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Pre destroy mysql database connection information"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_mysql_publish_conn_info
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source /etc/openshift/node.conf
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

for v in "OPENSHIFT_MYSQL_DB_GEAR_DNS" "OPENSHIFT_MYSQL_DB_GEAR_UUID" "OPENSHIFT_MYSQL_DB_HOST" \
         "OPENSHIFT_MYSQL_DB_PASSWORD" "OPENSHIFT_MYSQL_DB_PORT"      "OPENSHIFT_MYSQL_DB_SOCKET" \
         "OPENSHIFT_MYSQL_DB_URL"      "OPENSHIFT_MYSQL_DB_USERNAME";
do
    app_remove_env_var $v
done
