#require "bundler/gem_tasks"
require 'rake'
require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.test_files = FileList['test/**/*_test.rb']
  t.ruby_opts << '-I"../apachedb/lib"'
  t.ruby_opts << '-I"../../../node/lib"'
  t.ruby_opts << '-I"../../../node/test"'
  t.verbose = true
end
