#!/bin/bash

# Prepare to move to a new ip

# Exit on any errors
set -e

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/apache
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/network

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3

setup_basic_vars
cartridge_type="mongodb-2.2"

CART_INFO_DIR=${CARTRIDGE_BASE_PATH}/embedded/$cartridge_type/info
source ${CART_INFO_DIR}/lib/util

MONGODB_DIR="$APP_HOME/$cartridge_type/"

mkdir -p $MONGODB_DIR/.env
cp $APP_HOME/.env/OPENSHIFT_MONGODB_DB_HOST $MONGODB_DIR/.env
cp $APP_HOME/.env/OPENSHIFT_MONGODB_DB_PORT $MONGODB_DIR/.env
cp $APP_HOME/.env/OPENSHIFT_MONGODB_DB_PASSWORD $MONGODB_DIR/.env
cp $APP_HOME/.env/OPENSHIFT_MONGODB_DB_USERNAME $MONGODB_DIR/.env
