API:
  SEARCH_TEAMS:
    search: engineering
    global: true  
AUTHORIZATION:
  ADD_AUTHORIZATION:
    note: This is a note to myself
  UPDATE:
    note: This is my UPDATED note to myself

DOMAIN:
  ADD_DOMAIN: 
    name: mydomain
  UPDATE_MEMBERS:
   login: team.member@mycompany.com
   role: view
   type: user
  UPDATE:
    name: xmydomainx

APPLICATION:
  ADD_APPLICATION:
    name: myapp
    cartridges: ruby-1.9
    scale: true
  ACTIVATE:
    deployment_id: f36f59c0
  UPDATE:
    auto-deploy: false
    keep_deployments: 3
  SET_UNSET_ENVIRONMENT_VARIABLES:
    environment_variables:
    - name: FOO
      value: '123'
    - name: BAR
      value: abc
    
CARTRIDGE:
  ADD_CARTRIDGE:
    name: mysql-5.1
  UPDATE:
    additional_gear_storage: 10
    scales_to: 4

ENVIRONMENT_VARIABLE:
  ADD_ENVIRONMENT_VARIABLE:
    name: FOO
    value: bar
  UPDATE:
    name: FOO
    value: xbar

KEY:
  ADD_KEY:
    name: mykey
    type: ssh-rsa
    content: AAAAB3NzaC1yc2EAAAADAQABAAABAQDBJHobjmzxy8cv9A1xw9X5TlnQd0bW/19FwOC0c6jPNu9ZbtWQcAE0xfODl7ZqVPPU2qAFOh4rbL3gL2UzTyA+NwERyDrH7tMXAoXPT2L6sqExl0xxuEvb/lXUfLquMq+BMOFxxqCEg8X7GavHN72FMUHwweNybE7C82So+OFSWqFoctiWMNdNsKW4lvBd/jkIudGdRdK+/PzV75TW1LcpfsBrFOJZbd5WzDJEPNdMqOH68YDExD82VtzeJm0HEavhMY9HtxIDEmjIhtfedzCGZLe+6OxReuatw6M+n1sFxT9liprZ6NIANvbnYZKGT50hYfnIi/hZOTCvqYNS97O3
  UPDATE:
    type: ssh-rsa
    content: AAAAB3NzaC1yc2EAAAADAQABAAABAQCw6NXzjOTOrpQbzG4KjJXXRGLk6g8KCNjjMnqA34WA4SEPeCrCVbDPHlyY/2ygb3XRML/UhcImyzJfelQLSVmygUEzLn03ES3GhYKdyENDlp9mtMih8Dyk4g7CpqYoClIm/S9m2UrAvvt9fTcN6SatOXeOTayhLVvk3VJBYJQRL5c135mmqko90x8O8ixNAN1FP920jOVlHBFIFHePDFKvSfqjC7p8nIYvIowODZPk7vnI//m6lyDbKuxdwO5RnqyBHJtVST7+tyPuC3Kh0Y7tjAB/KsFMs5G+OTqT6b3gNPS6DoyGf6y1umGW1YepVc+pGcwLk93Ra9hU0GB1qA3t

ALIAS:
  ADD_ALIAS:
    id: myalias
    pass_phrase: abcd
  UPDATE:
    pass_phrase: abcd
    
TEAM:
  ADD_TEAM:
    name: myteam
  UPDATE_MEMBERS:
    login: team.member@mycompany.com
    role: view
    type: user
  SEARCH_TEAMS:
    search: engineering
    global: true  

MEMBER:
  ADD_MEMBER:
    login: team.member@mycompany.com
    role: view
    type: user
  UPDATE:
    role: view
    