#!/bin/bash

[ ! -z "$PSQL_LIB_UTIL" ] && return 0
PSQL_LIB_UTIL=true

function start_postgresql {
    PSQL_DIR=${PSQL_DIR:-"$APP_HOME/postgresql-8.4/"}
    super_run_as_user "$PSQL_DIR/${application}_postgresql_ctl.sh start"
    wait_to_start
}

function wait_to_start {
    i=0
    while (( PGPASSWORD="$OPENSHIFT_DB_PASSWORD" psql -U $OPENSHIFT_DB_USERNAME -h $OPENSHIFT_DB_HOST -l > /dev/null 2>&1) || [ ! -f ${PSQL_DIR}/pid/postgres.pid ]) && [ $i -lt 10 ]
    do
        sleep 1
        i=$(($i + 1))
    done
}


function stop_postgresql {
    PSQL_DIR=${PSQL_DIR:-"$APP_HOME/postgresql-8.4/"}
    super_run_as_user "$PSQL_DIR/${application}_postgresql_ctl.sh stop"
}

function start_postgresql_as_user {
    ${OPENSHIFT_DB_CTL_SCRIPT} start
}

function stop_postgresql_as_user {
    ${OPENSHIFT_DB_CTL_SCRIPT} stop
    sleep 1
}

function wait_to_start_as_user {
    if [ -n "$OPENSHIFT_DB_USERNAME" ]
    then
        i=0
        sleep 1
        while (( psql -l > /dev/null 2>&1) || [ ! -f ${PSQL_DIR}/pid/postgres.pid ]) && [ $i -lt 10 ]
        do
            sleep 1
            i=$(($i + 1))
        done
    fi
}
