#!/bin/bash

# Destroys jenkins client instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_jenkins_client_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

cartridge_type="jenkins-client-1.4"
source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_embedded_deconfigure "$1" $2 $3

JENKINS_CLIENT_DIR=$(get_cartridge_instance_dir "$cartridge_type")

#
# Remove environment variables
#
/bin/rm -rf $APP_HOME/.env/OPENSHIFT_CI_TYPE $APP_HOME/.env/PATH_JENKINS_CLIENT "$JENKINS_CLIENT_DIR"

. $APP_HOME/.env/OPENSHIFT_HOMEDIR
. $APP_HOME/.env/OPENSHIFT_APP_NAME
. $APP_HOME/.env/JENKINS_URL
. $APP_HOME/.env/JENKINS_USERNAME
. $APP_HOME/.env/JENKINS_PASSWORD

if [ -n "$JENKINS_URL" ]
then
  #
  # Disable job
  #
  if out=$(run_as_user "${CART_INFO_DIR}/bin/jenkins_job_action disable" 2>&1)
  then
      # Existing job was disabled
      client_result ""
      client_result "The corresponding job '${OPENSHIFT_GEAR_NAME}-build' in Jenkins has been disabled."
      client_result "You can re-enable or delete as desired."
  else
      # An error occurred disabling existing job
      client_result ""
      client_result "Could not disable job '${OPENSHIFT_GEAR_NAME}-build' in Jenkins server:"
      client_result "   $out"
      client_result "Continuing anyway."
  fi
  client_result "Job URL: ${JENKINS_URL}job/${OPENSHIFT_GEAR_NAME}-build/"
  client_result ""
fi
client_result "Jenkins client 1.4 has been removed from: $OPENSHIFT_GEAR_NAME"