#!/bin/bash

# Creates a thread dump from a jboss-as7 instance

# Exit on any errors
# set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Get a thread dump for a running application"

    echo "$0 $@" | logger -p local0.notice -t stickshift_threaddump
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_basic_hook "$1" $2 $3

#
# Get the thread dump
#

result=`run_as_user "$CARTRIDGE_BASE_PATH/ruby-1.8/info/bin/threaddump.sh $1 $3"`

if [$result .eq ""]; then
    DATE=`date '+%Y%m%d'`
    client_result "Success"
    client_result ""
    client_result "The thread dump file will be available via: rhc app tail -a ${application} -f ${application}/logs/error_log-$DATE-000000-EST -o '-n 250'"
else
    client_result " $result"
fi

