#!/bin/bash

# Publishes the mongodb database connection information.

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Publish mongodb database connection information"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_mongodb_publish_conn_info
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source /etc/openshift/node.conf
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_configure "$1" $2 $3

import_env_vars

# Check scalability and setup entries accordingly.
if is_a_scalable_app; then
    mongodb_host=$OPENSHIFT_GEAR_DNS
    mongodb_port=$OPENSHIFT_MONGODB_DB_PROXY_PORT
    mongodb_dburl="mongodb://$OPENSHIFT_MONGODB_DB_USERNAME:$OPENSHIFT_MONGODB_DB_PASSWORD@$mongodb_host:$mongodb_port/"
    echo -n "OPENSHIFT_MONGODB_DB_GEAR_UUID=$OPENSHIFT_GEAR_UUID; "
    echo -n "OPENSHIFT_MONGODB_DB_GEAR_DNS=$OPENSHIFT_GEAR_DNS; "
fi

echo -n "OPENSHIFT_MONGODB_DB_USERNAME=$OPENSHIFT_MONGODB_DB_USERNAME; "
echo -n "OPENSHIFT_MONGODB_DB_PASSWORD=$OPENSHIFT_MONGODB_DB_PASSWORD; "
echo -n "OPENSHIFT_MONGODB_DB_HOST=${mongodb_host:-$OPENSHIFT_MONGODB_DB_HOST}; "
echo -n "OPENSHIFT_MONGODB_DB_PORT=${mongodb_port:-$OPENSHIFT_MONGODB_DB_PORT}; "
echo -n "OPENSHIFT_MONGODB_DB_URL=${mongodb_dburl:-$OPENSHIFT_MONGODB_DB_URL}; "
echo ""
