#!/bin/bash

# Start the application httpd instance

# Exit on any errors
set -e

# Get gear ip address.
gip=$OPENSHIFT_PROXY_IP

if [ -z "$gip" ]; then
  gip=$(facter ipaddress)
fi

if [ -z "$gip" ]; then
   gip=$(python -c "import socket; print socket.gethostbyname('$(hostname)')")
fi

#
# Publish this gear's HTTP URL/endpoint.
#
echo "${OPENSHIFT_GEAR_DNS}|${gip}:${OPENSHIFT_PHP_PROXY_PORT}"
