#!/bin/bash

# Start the application httpd instance

# Exit on any errors
set -e

#
# Publish this gear's HTTP URL/endpoint.
#
echo "${OPENSHIFT_GEAR_DNS}|${OPENSHIFT_PROXY_IP}:${OPENSHIFT_PHP_PROXY_PORT}"
