#!/usr/bin/ruby

fp = File.open("#{ENV['OPENSHIFT_PHP_DIR']}/configuration/etc/conf.d/openshift.conf", "r")
out = []
fp.readlines.each { |line|
  items = line.split(' ')
  if items.length==3 and items[0]=="php_value" and items[1]=="include_path"
    new_value = items[2][0..-2]+":"+ARGV[0]
    out << new_value.dup
  else
    out << line
  end
}
fp.close

fp = File.open("#{ENV['OPENSHIFT_PHP_DIR']}/configuration/etc/conf.d/openshift.conf", "w")
fp.write(out.join('\n'))
fp.close

`#{ENV['OPENSHIFT_PHP_DIR']}/bin/control restart`

