source "https://rubygems.org"

# Specify your gem's dependencies in openshift-origin-node.gemspec
gemspec

# NON-RUNTIME BEGIN

# To simplify the packaging burden for distro maintainers it's important to
# place all gems not needed at runtime in this section.  It can be removed
# during package build time to avoid having to ship/support development-only
# packages.

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :test do
  gem 'simplecov'
end

# NON-RUNTIME END
