#!/bin/bash
#
# Destroys a Node instance (Node.js Application).
#


function print_help() {
   echo "Usage: $0 app-name namespace uuid"
   echo "$0 $@" | logger -p local0.notice -t openshift_origin_nodejs_deconfigure
   exit 1
}


#
# main():
#

# Parse arguments.
while getopts 'd' OPTION; do
   case $OPTION in
      d)  set -x      ;;
      ?)  print_help  ;;
   esac
done

# Ensure arguments.
[ $# -eq 3 ] || print_help

cartridge_type="nodejs-0.6"

# Source in common utility functions.
source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

# Deconfigure app.
setup_deconfigure "$1" $2 $3

source $APP_HOME/.env/OPENSHIFT_APP_UUID
container_uuid=$3
/usr/bin/oo-delete-endpoints --with-app-uuid $OPENSHIFT_APP_UUID --with-container-uuid $container_uuid --cart-name $cartridge_type

if [ ! -d "$APP_HOME/app-root" ]
then
    echo "${application}.  Application directory doesn't exist:  $APP_HOME/app-root"
else
    disable_cgroups

    # Destroy git repo and stop app.
    destroy_git_repo $application $uuid
    stop_app

    # Confirm stop + no activity in logs.
    NODEJS_INSTANCE_DIR=$(get_cartridge_instance_dir "$cartridge_type")
    confirm_pid_gone "$NODEJS_INSTANCE_DIR/run/nodejs.pid"
    confirm_log_files_inactive "$NODEJS_INSTANCE_DIR/logs"

    # Blow away the directories.
    rm_cartridge_instance_dir "$cartridge_type"
    
    enable_cgroups
fi


# And finally, remove virtualhost definition added to Apache.
oo-frontend-disconnect \
    --with-container-uuid "$uuid" \
    --with-container-name "$application" \
    --with-namespace "$namespace" \
    --path ""
