#!/bin/bash

# Move to a new ip

# Exit on any errors
set -e

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/apache
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/network

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3

setup_basic_vars

CART_INFO_DIR=${CARTRIDGE_BASE_PATH}/embedded/mysql-5.1/info
source ${CART_INFO_DIR}/lib/util

MYSQL_DIR="$APP_HOME/mysql-5.1/"

observe_setup_var_lib_dir "$MYSQL_DIR"

. $APP_HOME/.env/OPENSHIFT_INTERNAL_IP
IP=$OPENSHIFT_INTERNAL_IP

. $APP_HOME/.env/OPENSHIFT_DB_PORT
. $APP_HOME/.env/OPENSHIFT_DB_HOST
. $APP_HOME/.env/OPENSHIFT_DB_PASSWORD
. $APP_HOME/.env/OPENSHIFT_DB_USERNAME

ORIG_DB_HOST=$OPENSHIFT_DB_HOST

if [ "$ORIG_DB_HOST" != "$IP" ]
then
    echo "export OPENSHIFT_DB_HOST='$IP'" > $APP_HOME/.env/OPENSHIFT_DB_HOST
    echo "export OPENSHIFT_DB_URL='mysql://$OPENSHIFT_DB_USERNAME:$OPENSHIFT_DB_PASSWORD@$IP:$OPENSHIFT_DB_PORT/'" > $APP_HOME/.env/OPENSHIFT_DB_URL

    sed -i "s,$ORIG_DB_HOST,$IP," $MYSQL_DIR/etc/my.cnf

    start_mysql

    echo "
UPDATE user SET Host='$IP' WHERE Host='$ORIG_DB_HOST';
flush privileges;" | mysql -u $OPENSHIFT_DB_USERNAME -P $OPENSHIFT_DB_PORT -h $IP --password="$OPENSHIFT_DB_PASSWORD" -S "${MYSQL_DIR}/socket/mysql.sock" mysql > /dev/null || error "Failed to setup root user with new ip" 187

    stop_mysql

    set_app_info "Connection URL: mysql://$IP:$OPENSHIFT_DB_PORT/"
fi