#!/bin/bash

# Remove httpd proxy

# Exit on any errors
set -e

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Remove httpd proxy for an application"

    echo "$0 $@" | logger -p local0.notice -t stickshift_remove_httpd_proxy
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3

APP_HOME="$GEAR_BASE_DIR/$uuid"

. $APP_HOME/.env/OPENSHIFT_GEAR_TYPE

# Only do this for an "standalone" mysql gear.
[ "$OPENSHIFT_GEAR_TYPE" = "mysql-5.1" ]  ||  return 0

rm_unobfuscated_app_home $namespace $application

rm -rf "/etc/httpd/conf.d/stickshift/${uuid}_${namespace}_${application}.conf" "/etc/httpd/conf.d/stickshift/${uuid}_${namespace}_${application}"
