#!/bin/bash

# Stops instance

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Stop a running application and disable it"

    echo "$0 $@" | logger -p local0.notice -t stickshift_mysql_stop
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_basic_hook "$1" $2 $3

MYSQL_DIR="$APP_HOME/mysql-5.1/"

#
# Start application
#
super_run_as_user "$MYSQL_DIR/${application}_mysql_ctl.sh stop"
touch "$MYSQL_DIR/run/stop_lock"