source "https://rubygems.org"

# Specify your gem's dependencies in openshift-origin-common.gemspec
gemspec

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :test do
  gem 'simplecov'
end
