require 'rake/clean'
require 'rake/testtask'

desc "Print environment to run from checkout - eval $( rake local_env | tail -n +1 )"
task :local_env do
  pwd = Dir.pwd
  puts "RUBYLIB='#{pwd}/lib/'; export RUBYLIB"
end

desc "Unit tests"
Rake::TestTask.new(:test) do |t|
  t.libs << File.expand_path('../lib', __FILE__)
  t.libs << File.expand_path('../test', __FILE__)
  t.libs << File.expand_path('../test/unit', __FILE__)
  t.pattern = 'test/unit/**/*_test.rb'
end

desc "Generate RDoc"
task :doc do
  sh "rdoc ."
end

# include standard build and doc tasks
require "../tasks/yard_tasks"
require "../tasks/build_tasks"

YARD_SOURCEROOT = File.dirname(__FILE__)
YARD_SOURCES = ['lib']
