#!/bin/bash

# Publishes the mysql database connection information.

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Publish mysql database connection information"

    echo "$0 $@" | logger -p local0.notice -t stickshift_mysql_publish_conn_info
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source /etc/stickshift/stickshift-node.conf
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_configure "$1" $2 $3

import_env_vars

# Check scalability and setup entries accordingly.
if is_a_scalable_app; then
    mysql_host=$OPENSHIFT_GEAR_DNS
    mysql_port=$OPENSHIFT_DB_PROXY_PORT
    mysql_dburl="$OPENSHIFT_DB_TYPE://$OPENSHIFT_DB_USERNAME:$OPENSHIFT_DB_PASSWORD@$mysql_host:$mysql_port/"
    mysql_dbsocket=""
    echo -n "OPENSHIFT_DB_GEAR_UUID=$OPENSHIFT_GEAR_UUID; "
    echo -n "OPENSHIFT_DB_GEAR_DNS=$OPENSHIFT_GEAR_DNS; "
    echo -n "OPENSHIFT_DB_CTL_ONGEAR_SCRIPT=$OPENSHIFT_DB_CTL_SCRIPT; "
fi

echo -n "OPENSHIFT_DB_TYPE=$OPENSHIFT_DB_TYPE; "
echo -n "OPENSHIFT_DB_USERNAME=$OPENSHIFT_DB_USERNAME; "
echo -n "OPENSHIFT_DB_PASSWORD=$OPENSHIFT_DB_PASSWORD; "
echo -n "OPENSHIFT_DB_HOST=${mysql_host:-$OPENSHIFT_DB_HOST}; "
echo -n "OPENSHIFT_DB_PORT=${mysql_port:-$OPENSHIFT_DB_PORT}; "
echo -n "OPENSHIFT_DB_URL=${mysql_dburl:-$OPENSHIFT_DB_URL}; "
echo -n "OPENSHIFT_DB_SOCKET=${mysql_dbsocket:-$OPENSHIFT_DB_SOCKET}; "
echo -n "OPENSHIFT_DB_MYSQL_51_DUMP=$OPENSHIFT_DB_MYSQL_51_DUMP; "
echo -n "OPENSHIFT_DB_MYSQL_51_DUMP_CLEANUP=$OPENSHIFT_DB_MYSQL_51_DUMP_CLEANUP; "
echo -n "OPENSHIFT_DB_MYSQL_51_EMBEDDED_TYPE=$OPENSHIFT_DB_MYSQL_51_EMBEDDED_TYPE; "
echo -n "OPENSHIFT_DB_MYSQL_51_RESTORE=$OPENSHIFT_DB_MYSQL_51_RESTORE; "
echo ""

