#!/bin/bash
# Utility functions for 10gen cartridge installation

export OPENSHIFT_MMS_BASE_DIR=${OPENSHIFT_DATA_DIR}mms-agent
export OPENSHIFT_MMS_SOURCES_DIR=${OPENSHIFT_REPO_DIR}/.openshift/mms

function agent_sources_exists {
  stat -t ${OPENSHIFT_MMS_SOURCES_DIR}/mongodb-mms-monitoring-agent*.tar.gz &>/dev/null
}

function is_agent_installed {
  [ -f "${OPENSHIFT_MMS_BASE_DIR}/monitoring-agent.config" ]
}

function install_agent_sources {
  if ! agent_sources_exists; then
    client_error ""
    client_error "Missing mongodb-mms-monitoring-agent.tar.gz, which needs to be git pushed in the .openshift/mms/ directory in your repository."
    client_error "The tarball is available after registration at https://mms.mongodb.com, in the Settings -> Monitoring Agent section."
    exit 0
  fi
  pushd $OPENSHIFT_MMS_BASE_DIR >/dev/null
  echo "Installing MMS agent sources..."
  tar --strip-components=1 -xzvf \
    ${OPENSHIFT_MMS_SOURCES_DIR}/mongodb-mms-monitoring-agent*.tar.gz \
    -C ${OPENSHIFT_MMS_BASE_DIR}
  if [ $? -gt 0 ]; then
    client_error "Error during extracting the mongodb mms agent archive."
    return 1
  fi
  if ! is_agent_installed; then
    client_error "Extracted archive doesn't contain monitoring-agent.config file."
    client_error "Please download the tarball at the https://mms.mongodb.com, in the Settings -> Monitoring Agent section."
    return 1
  fi
  popd >/dev/null
  return 0
}
