#!/bin/bash

# Adds a gear to the haproxy configuration.

# Exit on any errors
set -e

list=
kvargs=$(echo "${@:4}" | tr -d "\n" )
for arg in $kvargs; do
    ip=$(echo "$arg" | cut -f 2 -d '=' | tr -d "'")
    ip=`echo "$ip" | sed "s/:/[/g"`
    if [ -z "$list" ]; then
        list="export OPENSHIFT_JBOSS_CLUSTER=$ip]"
    else
        list="$list,$ip]"
    fi
done

echo "$list" > /var/lib/stickshift/$3/.env/OPENSHIFT_JBOSS_CLUSTER


