#!/bin/bash

[ ! -z "$MONGODB_LIB_UTIL" ] && return 0
MONGODB_LIB_UTIL=true

function start_mongodb {
    super_run_as_user "$MONGODB_DIR/${application}_mongodb_ctl.sh start"
    wait_to_start
}

function restart_mongodb {
    super_run_as_user "$MONGODB_DIR/${application}_mongodb_ctl.sh restart"
    wait_to_start
}

function wait_to_start {
    i=0
    while (( ! echo "exit" | mongo $IP > /dev/null 2>&1) ||  \
             [ ! -f ${MONGODB_DIR}/pid/mongodb.pid ]) && [ $i -lt 10 ]
    do
        sleep 1
        i=$(($i + 1))
    done
}


function stop_mongodb {
    super_run_as_user "$MONGODB_DIR/${application}_mongodb_ctl.sh stop"
}

function repair_mongodb {
    super_run_as_user "$MONGODB_DIR/${application}_mongodb_ctl.sh repair"
}

function start_mongodb_as_user {
    ${OPENSHIFT_NOSQL_DB_CTL_SCRIPT} start
    wait_to_start
}

function stop_mongodb_as_user {
    ${OPENSHIFT_NOSQL_DB_CTL_SCRIPT} stop
    sleep 1
}

