#!/bin/bash

# Publishes the mysql database connection information.

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Publish mysql database connection information"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_mysql_publish_conn_info
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source /etc/openshift/node.conf
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_configure "$1" $2 $3

import_env_vars

# Check scalability and setup entries accordingly.
if is_a_scalable_app; then
    mysql_host=$OPENSHIFT_GEAR_DNS
    mysql_port=$OPENSHIFT_MYSQL_DB_PROXY_PORT
    mysql_dburl="mysql://$OPENSHIFT_MYSQL_DB_USERNAME:$OPENSHIFT_MYSQL_DB_PASSWORD@$mysql_host:$mysql_port/"
    mysql_dbsocket=""
    echo -n "OPENSHIFT_MYSQL_DB_GEAR_UUID=$OPENSHIFT_GEAR_UUID; "
    echo -n "OPENSHIFT_MYSQL_DB_GEAR_DNS=$OPENSHIFT_GEAR_DNS; "
fi

echo -n "OPENSHIFT_MYSQL_DB_USERNAME=$OPENSHIFT_MYSQL_DB_USERNAME; "
echo -n "OPENSHIFT_MYSQL_DB_PASSWORD=$OPENSHIFT_MYSQL_DB_PASSWORD; "
echo -n "OPENSHIFT_MYSQL_DB_HOST=${mysql_host:-$OPENSHIFT_MYSQL_DB_HOST}; "
echo -n "OPENSHIFT_MYSQL_DB_PORT=${mysql_port:-$OPENSHIFT_MYSQL_DB_PORT}; "
echo -n "OPENSHIFT_MYSQL_DB_URL=${mysql_dburl:-$OPENSHIFT_MYSQL_DB_URL}; "
echo ""

