#!/bin/bash

# Move to a new ip

# Exit on any errors
set -e

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/apache
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/network

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

namespace=`basename $2`
application="$1"
uuid=$3

CART_NAME="postgresql"
CART_VERSION="8.4"
cartridge_type="$CART_NAME-$CART_VERSION"

setup_basic_vars
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

CART_INSTANCE_DIR=$(get_cartridge_instance_dir "$cartridge_type")
CART_INFO_DIR=${CARTRIDGE_BASE_PATH}/embedded/$cartridge_type/info
CART_ETC_DIR=$CART_INFO_DIR/configuration/etc
source ${CART_INFO_DIR}/lib/util

observe_setup_var_lib_dir "$CART_INSTANCE_DIR"

source_if_exists "$APP_HOME/.env/OPENSHIFT_INTERNAL_IP"
IP=$OPENSHIFT_INTERNAL_IP

# This gear is dedicated to running postgresql - configure it as such.
if [ -z "$IP" ]; then
    prepare_gear_for_standalone_postgresql
else
    . $APP_HOME/.env/OPENSHIFT_INTERNAL_IP
    IP=`find_open_ip $uid $uuid`
    if [ "$IP" != "$OPENSHIFT_INTERNAL_IP" ]; then 
       echo "export OPENSHIFT_INTERNAL_IP='$IP'" > $APP_HOME/.env/OPENSHIFT_INTERNAL_IP
    fi
    
    . $APP_HOME/.env/OPENSHIFT_APP_NAME
    if [ ! -d "$GEAR_BASE_DIR/$uuid/$OPENSHIFT_APP_NAME" ]; then
        #  This gear is dedicated to running postgresql - configure it as such.
        export CART_INFO_DIR
        import_env_vars
        $CART_INFO_DIR/bin/deploy_httpd_proxy.sh $application $namespace $uuid $IP
        restart_httpd_graceful
    fi
fi

# Create simple PostgreSQL start / stop script
ln -sf $CART_INFO_DIR/bin/postgresql_ctl.sh $CART_INSTANCE_DIR/${application}_postgresql_ctl.sh
OPENSHIFT_DB_CTL_SCRIPT="$CART_INSTANCE_DIR/${application}_postgresql_ctl.sh"

#
# Fix permissions
#
old_uuid=$(stat -c %U $CART_INSTANCE_DIR/etc)
if [ ! "$old_uuid" == "$uuid" ]; then
    pushd "$CART_INSTANCE_DIR" > /dev/null
    chown -cR --from=$old_uuid.$old_uuid $uuid.$uuid * > /dev/null
    popd > /dev/null
fi

#
# Source database connection variables
#
if [ -d $CART_INSTANCE_DIR/.env ]; then
    . $CART_INSTANCE_DIR/.env/OPENSHIFT_DB_PORT
    . $CART_INSTANCE_DIR/.env/OPENSHIFT_DB_HOST
    . $CART_INSTANCE_DIR/.env/OPENSHIFT_DB_PASSWORD
    . $CART_INSTANCE_DIR/.env/OPENSHIFT_DB_USERNAME
    rm -rf $CART_INSTANCE_DIR/.env
else
    . $APP_HOME/.env/OPENSHIFT_DB_PORT
    . $APP_HOME/.env/OPENSHIFT_DB_HOST
    . $APP_HOME/.env/OPENSHIFT_DB_PASSWORD
    . $APP_HOME/.env/OPENSHIFT_DB_USERNAME
fi

#
# Setup Environment Variables
#
echo "export OPENSHIFT_DB_USERNAME='$OPENSHIFT_DB_USERNAME'" > $APP_HOME/.env/OPENSHIFT_DB_USERNAME
echo "export OPENSHIFT_DB_PASSWORD='$OPENSHIFT_DB_PASSWORD'" > $APP_HOME/.env/OPENSHIFT_DB_PASSWORD
echo "export OPENSHIFT_DB_TYPE='postgresql'" > $APP_HOME/.env/OPENSHIFT_DB_TYPE
echo "export OPENSHIFT_DB_HOST='$IP'" > $APP_HOME/.env/OPENSHIFT_DB_HOST
echo "export OPENSHIFT_DB_PORT='5432'" > $APP_HOME/.env/OPENSHIFT_DB_PORT
echo "export OPENSHIFT_DB_SOCKET='${CART_INSTANCE_DIR}/socket/postgres.sock'" > $APP_HOME/.env/OPENSHIFT_DB_SOCKET
echo "export OPENSHIFT_DB_URL='postgresql://$OPENSHIFT_DB_USERNAME:$OPENSHIFT_DB_PASSWORD@$IP:5432/'" > $APP_HOME/.env/OPENSHIFT_DB_URL
echo "export OPENSHIFT_DB_CTL_SCRIPT='$CART_INSTANCE_DIR/${application}_postgresql_ctl.sh'" > $APP_HOME/.env/OPENSHIFT_DB_CTL_SCRIPT
echo "export OPENSHIFT_DB_POSTGRESQL_84_DUMP='$CART_INFO_DIR/bin/postgresql_dump.sh'" > $APP_HOME/.env/OPENSHIFT_DB_POSTGRESQL_84_DUMP
echo "export OPENSHIFT_DB_POSTGRESQL_84_DUMP_CLEANUP='$CART_INFO_DIR/bin/postgresql_cleanup.sh'" > $APP_HOME/.env/OPENSHIFT_DB_POSTGRESQL_84_DUMP_CLEANUP
echo "export OPENSHIFT_DB_POSTGRESQL_84_RESTORE='$CART_INFO_DIR/bin/postgresql_restore.sh'" > $APP_HOME/.env/OPENSHIFT_DB_POSTGRESQL_84_RESTORE
echo "export OPENSHIFT_DB_POSTGRESQL_84_EMBEDDED_TYPE='postgresql-8.4'" > $APP_HOME/.env/OPENSHIFT_DB_POSTGRESQL_84_EMBEDDED_TYPE

ORIG_DB_HOST=$OPENSHIFT_DB_HOST

if [ "$ORIG_DB_HOST" != "$IP" ]
then
    sed -i "s,$ORIG_DB_HOST,$IP," $CART_INSTANCE_DIR/data/postgresql.conf
    sed -i "s,$old_uuid,$uuid," $CART_INSTANCE_DIR/data/postgresql.conf
    echo "$IP:$OPENSHIFT_DB_PORT:*:$OPENSHIFT_DB_USERNAME:$OPENSHIFT_DB_PASSWORD" > $APP_HOME/.pgpass
    set_app_info "Connection URL: postgresql://$IP:$OPENSHIFT_DB_PORT/"
fi
