#!/bin/bash

# Exit on any errors
set -e

list=
kvargs=$(echo "${@:4}" | tr -d "\n" )
for arg in $kvargs; do
    ip=$(echo "$arg" | cut -f 2 -d '=' | tr -d "'")
    ip=`echo "$ip" | sed "s/:/[/g"`
    if [ -z "$list" ]; then
        list="$ip]"
    else
        list="$list,$ip]"
    fi
done

if [ -f /var/lib/stickshift/$3/.env/OPENSHIFT_JBOSS_HAPROXY_CLUSTER ]
then
  source /var/lib/stickshift/$3/.env/OPENSHIFT_JBOSS_HAPROXY_CLUSTER
  echo "export OPENSHIFT_JBOSS_CLUSTER=$list,$OPENSHIFT_JBOSS_HAPROXY_CLUSTER" > /var/lib/stickshift/$3/.env/OPENSHIFT_JBOSS_CLUSTER
  rm -f /var/lib/stickshift/$3/.env/OPENSHIFT_JBOSS_HAPROXY_CLUSTER
else
  echo "export OPENSHIFT_JBOSS_HAPROXY_CLUSTER=$list" > /var/lib/stickshift/$3/.env/OPENSHIFT_JBOSS_HAPROXY_CLUSTER
fi


