#!/bin/bash

[ ! -z "$MYSQL_LIB_UTIL" ] && return 0
MYSQL_LIB_UTIL=true

function start_mysql {
    super_run_as_user "$MYSQL_DIR/${application}_mysql_ctl.sh start"
    wait_to_start
}

function wait_to_start {
    i=0
    while (( ! echo ";" | mysql -u root -S "${MYSQL_DIR}/socket/mysql.sock" > /dev/null 2>&1) || [ ! -f ${MYSQL_DIR}/pid/mysql.pid ]) && [ $i -lt 10 ]
    do
        sleep 1
        i=$(($i + 1))
    done
}


function stop_mysql {
    super_run_as_user "$MYSQL_DIR/${application}_mysql_ctl.sh stop"
}

function control_mysql_on_dbgear {
   gear_user_and_host="$OPENSHIFT_DB_GEAR_UUID@$OPENSHIFT_DB_GEAR_DNS"
   ssh $gear_user_and_host rhcsh $OPENSHIFT_DB_CTL_ONGEAR_SCRIPT start
}

function start_mysql_as_user {
    if [[ -n "$OPENSHIFT_DB_GEAR_UUID"  &&  -n "$OPENSHIFT_DB_GEAR_DNS"  &&
          "$OPENSHIFT_APP_UUID" != "$OPENSHIFT_DB_GEAR_UUID" ]]; then
        control_mysql_on_dbgear start
        return 0
    fi

    ${OPENSHIFT_DB_CTL_SCRIPT} start
}

function stop_mysql_as_user {
    if [[ -n "$OPENSHIFT_DB_GEAR_UUID"  &&  -n "$OPENSHIFT_DB_GEAR_DNS"  &&
          "$OPENSHIFT_APP_UUID" != "$OPENSHIFT_DB_GEAR_UUID" ]]; then
        control_mysql_on_dbgear stop
        sleep 1
        return 0
    fi

    ${OPENSHIFT_DB_CTL_SCRIPT} stop
    sleep 1
}

function wait_to_start_as_user {
    if [ -n "$OPENSHIFT_DB_USERNAME" ]
    then
        i=0
        sleep 1
        while (( ! echo ";" | mysql -h $OPENSHIFT_DB_HOST -P $OPENSHIFT_DB_PORT -u $OPENSHIFT_DB_USERNAME --password="$OPENSHIFT_DB_PASSWORD" > /dev/null 2>&1) || [ ! -f ${MYSQL_DIR}/pid/mysql.pid ]) && [ $i -lt 10 ]
        do
            sleep 1
            i=$(($i + 1))
        done
    fi
}
