source 'https://rubygems.org'

gemspec

gem 'pry', :require => 'pry' if ENV['PRY']
gem 'perftools.rb', :require => 'perftools' if ENV['PERFTOOLS']
gem 'syslog-logger', '~> 1.6.8', :require => false

# NON-RUNTIME BEGIN

# To simplify the packaging burden for distro maintainers it's important to
# place all gems not needed at runtime in this section.  It can be removed
# during package build time to avoid having to ship/support development-only
# packages.

group :test do
  gem 'ci_reporter',   '>= 1.7.0', :require => false
  gem 'minitest',      '~> 3.5.0', :require => false
  gem 'mocha',         '~> 0.13.3', :require => false
  gem 'simplecov',     '~> 0.6.4', :require => false
  gem 'webmock',       '~> 1.8.0', :require => false
  gem 'poltergeist',   '~> 1.2.0', :require => false
  gem 'capybara',      '~> 2.1.0', :require => false

  # Note:  Only for CI output
  gem 'rspec-core',    '~> 2.8', :require => false
end

group :test, :development do
  gem 'konacha',       '~> 2.6.0'
end

# NON-RUNTIME END

group :assets do
  gem 'compass-rails', '~> 1.0.3'
  gem 'sass-rails',    '~> 3.2.5'
  gem 'coffee-rails',  '~> 3.2.2'
  gem 'jquery-rails',  '~> 3.1.0'
  gem 'uglifier',      '>= 1.2.6'
  gem 'therubyracer',  '>= 0.10'
  gem 'sass-twitter-bootstrap',  '2.0.1'
end
