#!/usr/bin/env rake

if defined? Rails then
  begin
   require 'bundler/setup'
  rescue LoadError
    puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
  end

  APP_RAKEFILE = File.expand_path(
    "test/rails_app/Rakefile", 
    File.dirname(__FILE__))

  load 'rails/tasks/engine.rake'

  Bundler::GemHelper.install_tasks
  #
  # Bundler has an older vendored version of net/http/persistent in /vendor. 
  # If this remains on the path, then calling require 'net/http/persistent'
  # will load the vendored version rather than the one on our path.
  #
  $LOAD_PATH.delete_if{ |p| p =~ %r(/lib/bundler/vendor) }

else
  require 'rake/testtask'


  begin
    require 'rdoc/task'
  rescue LoadError
    require 'rdoc/rdoc'
    require 'rake/rdoctask'
    RDoc::Task = Rake::RDocTask
  end

  RDoc::Task.new(:rdoc) do |rdoc|
    rdoc.rdoc_dir = 'rdoc'
    rdoc.title    = 'Testblah'
    rdoc.options << '--line-numbers'
    rdoc.rdoc_files.include('README.rdoc')
    rdoc.rdoc_files.include('lib/**/*.rb')
  end


  Rake::TestTask.new(:test) do |t|
    t.libs << 'lib'
    t.libs << 'test'
    t.pattern = 'test/**/*_test.rb'
    t.verbose = false
  end

  # include standard build and documentation tasks
  require "../tasks/build_tasks"
  require "../tasks/yard_tasks"

  YARD_SOURCEROOT = File.dirname(__FILE__)
  # Define these to allow generation of comprehensive yard docs
  YARD_SOURCES = ['app', 'config', 'lib']  
  

  task :default => :test
end
