#!/usr/bin/env rake

begin
  require 'rdoc/task'
rescue LoadError
  require 'rdoc/rdoc'
  require 'rake/rdoctask'
  RDoc::Task = Rake::RDocTask
end

RDoc::Task.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title    = 'OpenShift Origin Console'
  rdoc.options << '--line-numbers'
  rdoc.rdoc_files.include('README.rdoc')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

ENGINE_PATH = File.expand_path("..", __FILE__)
APP_RAKEFILE = File.expand_path("../test/rails_app/Rakefile", __FILE__)

if defined? Bundler
  load 'rails/test_unit/testing.rake'

  ENGINE_STATS_DIRECTORIES = [
    %w(Controllers        app/controllers),
    %w(Helpers            app/helpers),
    %w(Models             app/models),
    %w(Libraries          lib/),
    %w(APIs               app/apis),
    %w(Integration\ tests test/integration),
    %w(Functional\ tests  test/functional),
    %w(Unit\ tests        test/unit)
  ].collect { |name, dir| [ name, "#{ENGINE_PATH}/#{dir}" ] }.select { |name, dir| File.directory?(dir) }

  desc "Report code statistics (KLOCs, etc) from the application"
  task :stats do
    require 'rails/code_statistics'
    CodeStatistics.new(*ENGINE_STATS_DIRECTORIES).to_s
  end

  Bundler::GemHelper.install_tasks

  Dir.glob('**/tasks/*.rake').each { |r| import r }
else
  import 'lib/tasks/version.rake'
end

