#!/bin/bash

# Restart the application

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Get application status"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_httpd_restart
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

cartridge_type=$(get_cartridge_name_from_path)

setup_basic_hook "$1" $2 $3

#
# Restart application
#
_state=`get_app_state`
set_app_state started
rm -f "$APP_DIR/run/stop_lock"
if [ "$_state" = "stopped" ] || [ "$_state" = "idle" ]
then
    start_app
else
    run_as_user "${CARTRIDGE_BASE_PATH}/${cartridge_type}/info/bin/app_ctl.sh restart" 
fi
