#!/bin/bash

# Stop the application httpd instance

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Stop a running application and disable it"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_httpd_stop
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

cartridge_type=$(get_cartridge_name_from_path)

setup_basic_hook "$1" $2 $3

#
# Stop application
#
stop_app
touch "$APP_DIR/run/stop_lock"
