#!/bin/bash

# Creates a thread dump from a jboss-as7 instance

# Exit on any errors
#set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "View system messages for a running application"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_system-messages
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_basic_hook "$1" $2 $3

result=`grep $3 /var/log/messages`

client_result "Success"
client_result ""

client_result "`echo $result`"
