#!/bin/bash

# Import Environment Variables
for f in ~/.env/*
do
    . $f
done

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

# Clean up logs in a generic fashion
for logdir in `awk 'BEGIN {
                           for (a in ENVIRON)
                           if (a ~ /LOG_DIR$/)
                           print ENVIRON[a] }'`
do
    client_message "Emptying log dir: ${logdir}"
    rm -rf ${logdir}* ${logdir}.[^.]*
done
