#!/bin/bash

# Destroys phpmyadmin instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t stickshift_phpmyadmin_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

app_type="phpmyadmin-3.4"
setup_embedded_deconfigure "$1" $2 $3

PHPMYADMIN_DIR=`echo $APP_HOME/phpmyadmin-3.4 | tr -s /` # ensure that there aren't double /'s
PHPMYADMIN_CTL_SCRIPT="$PHPMYADMIN_DIR/${application}_phpmyadmin_ctl.sh"

#
# Stop app
#
run_as_user "$PHPMYADMIN_CTL_SCRIPT stop" || warning "Failed to stop ${application}" 121

confirm_pid_gone "${PHPMYADMIN_DIR}/run/httpd.pid"

confirm_log_files_inactive "$PHPMYADMIN_DIR/logs"

#
# Remove environment variables
#
/bin/rm -f $APP_HOME/.env/OPENSHIFT_PHPMYADMIN_GEAR_DIR $APP_HOME/.env/OPENSHIFT_PHPMYADMIN_CTL_SCRIPT $APP_HOME/.env/OPENSHIFT_PHPMYADMIN_IP


# Remove phpmyadmin dir. This MUST be after stopping phpmyadmin as the CTL script relies on these.
runcon -l s0-s0:c0.c1023 rm -rf "$PHPMYADMIN_DIR"

#
# Remove ProxyPass definition from apache
#
rm -f /etc/httpd/conf.d/stickshift/${uuid}_${namespace}_${application}/phpmyadmin-3.4.conf || warning "Could not remove phpmyadmin apache definition" 156

/sbin/service httpd configtest 2> /dev/null && /sbin/service httpd graceful || warning "Failed to restart master httpd, please contact support" 120
