source 'http://rubygems.org'

gem 'rails', '~> 3.2.8'
gem 'json'
gem 'parseconfig', '0.5.2'
gem 'xml-simple'
gem 'rack'
gem 'regin'
gem 'open4'
gem 'openshift-origin-controller'
gem 'rest-client'
gem 'systemu'
gem 'minitest'
gem 'mongoid'

# Load plugin gems.
Dir["/etc/openshift/plugins.d/*.conf"].delete_if{ |x| x.end_with? "-dev.conf" }.map{|x| File.basename(x, ".conf")}.each {|plugin| gem plugin}

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19', :require => 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  # The require part from http://tinyurl.com/3pf68ho
  gem 'mocha', '0.12.1', :require => nil
  gem 'rake', '>= 0.8.7', '<= 0.9.2.2'
  gem 'cucumber'
end
