source 'http://rubygems.org'

gem 'minitest'
gem 'openshift-origin-console', :require => 'console', :path => ENV['CONSOLE_PATH']
group :assets do
        gem 'compass-rails', '~> 1.0.3'
        gem 'coffee-rails',  '~> 3.2.2'
        gem 'jquery-rails',  '~> 2.0.2'
        gem 'uglifier',      '>= 1.2.6'
        gem 'therubyracer',  '>= 0.10'
        gem 'sass-rails',    '~> 3.2.5'
end
