#!/bin/bash
#
# stickshift-proxy
#
# chkconfig:   345 85 15
# description: Stickshift proxy
# processname: haproxy
# config:      /etc/stickshift/stickshift-proxy.cfg
# pidfile:     /var/run/stickshift-proxy.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

[ -e /etc/sysconfig/stickshift-proxy ] && source /etc/sysconfig/stickshift-proxy

exec=/usr/sbin/haproxy
prog=haproxy
lockfile=/var/lock/subsys/stickshift-proxy
pidfile=/var/run/stickshift-proxy.pid
cfgfile=/var/lib/stickshift/.stickshift-proxy.d/stickshift-proxy.cfg

pre_start() {
    # Fix internal ip address in case it was changed by the cloud provider
    stickshift-proxy-cfg fixaddr
}

start() {
    echo -n $"Starting stickshift-proxy: "
    daemon --pidfile $pidfile $exec -D -f $cfgfile -p $pidfile
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping stickshift-proxy: "
    killproc -p $pidfile $prog 
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    echo -n $"Reloading stickshift-proxy: "
    $exec -D -f $cfgfile -p $pidfile -sf $(cat $pidfile)
    retval=$?
    echo
    return $retval
}

case "$1" in
    start)
        pre_start
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    reload)
        reload
        ;;
    status)
        status -p $pidfile $prog
        ;;
    condrestart|try-restart)
  	if [ -f $lockfile ] 
        then
            restart
        fi
	;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|reload}"
        exit 2
esac
