#require "bundler/gem_tasks"
require 'rake'
require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
end

namespace :test do

  Rake::TestTask.new(:functional) do |t|
    t.libs << 'test'
    t.test_files = FileList['test/functional/*_test.rb']
    t.verbose = true
  end

end
