#
# Standard Tasks
#
require "../tasks/build_tasks"
require "../tasks/yard_tasks"

YARD_SOURCEROOT = File.dirname(__FILE__)
YARD_SOURCES = ['app', 'config', 'lib']


#
# Custom test task
#
require 'rake/testtask'
Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
end

