#!/bin/bash -e
# Exit on any errors

list=
args=($(printf "%s\n" "${@:4}"))
for arg in "${args[@]}" ; do
    # skip if it's not a k/v arg
    [[ "${arg}" =~ '=' ]] || continue
    # drop single-quotes
    arg="${arg//\'/}"
    # grab the 'value' bit
    arg="${arg#*=}"
    # trim whitespace
    ip="${arg/:/[}"
    if [ -z "$list" ]; then
        list="$ip]"
    else
        list="$list,$ip]"
    fi
done

echo $list > $OPENSHIFT_JBOSSEAP_DIR/env/OPENSHIFT_JBOSSEAP_CLUSTER
