#!/bin/bash -eu

# Adds a gear to the haproxy configuration.

list=
kvargs=$(echo "${@:4}" | tr -d "\n" )
for arg in $kvargs; do
    ip=$(echo "$arg" | cut -f 2 -d '=' | tr -d "'")
    ip=$(echo "$ip" | sed "s/:/[/g")
    if [ -z "$list" ]; then
        list="$ip]"
    else
        list="$list,$ip]"
    fi
done

echo $list > $OPENSHIFT_JBOSSEAP_DIR/env/OPENSHIFT_JBOSSEAP_CLUSTER_REMOTING
