#!/bin/bash

# Exit on any errors
set -e

source $OPENSHIFT_CARTRIDGE_SDK_BASH

list=
kvargs=$(echo "${@:4}" | tr -d "\n" )
for arg in $kvargs; do
    ip=$(echo "$arg" | cut -f 2 -d '=' | tr -d "'")
    ip=$(echo "$ip" | sed "s/:/[/g")
    if [[ ! $ip  =~ $OPENSHIFT_GEAR_DNS ]]
    then
        if [ -z "$list" ]; then
            list="$ip]"
        else
            list="$list,$ip]"
        fi
    fi
done

# put this gear first in the list of hosts
if [ -z "$list" ]; then
    list="${OPENSHIFT_GEAR_DNS}[${OPENSHIFT_JBOSSEAP_CLUSTER_PROXY_PORT}]"
else
    list="${OPENSHIFT_GEAR_DNS}[${OPENSHIFT_JBOSSEAP_CLUSTER_PROXY_PORT}],$list"
fi

echo $list > $OPENSHIFT_JBOSSEAP_DIR/env/OPENSHIFT_JBOSSEAP_CLUSTER
