#!/bin/bash

# Exit on any errors
set -e

source $OPENSHIFT_CARTRIDGE_SDK_BASH

list=
kvargs=$(echo "${@:4}" | tr -d "\n" )
for arg in $kvargs; do
    ip=$(echo "$arg" | cut -f 2 -d '=' | tr -d "'")
    ip=`echo "$ip" | sed "s/:/[/g"`
    if [ -z "$list" ]; then
        list="$ip]"
    else
        list="$list,$ip]"
    fi
done

if [ -z "$OPENSHIFT_JBOSSEAP_TMP_CLUSTER" ]; then
  set_uservars "OPENSHIFT_JBOSSEAP_CLUSTER=$list,$OPENSHIFT_JBOSSEAP_TMP_CLUSTER"
else
  set_uservars "OPENSHIFT_JBOSSEAP_TMP_CLUSTER=${list}"
fi

