#!/bin/bash

# Adds a gear to the haproxy configuration.

# Exit on any errors
set -e

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

CART_NS=$(get_cartridge_namespace_from_path)

list=
kvargs=$(echo "${@:4}" | tr -d "\n" )
for arg in $kvargs; do
    ip=$(echo "$arg" | cut -f 2 -d '=' | tr -d "'")
    ip=`echo "$ip" | sed "s/:/[/g"`
    if [ -z "$list" ]; then
        list="$ip]"
    else
        list="$list,$ip]"
    fi
done

if [ -f /var/lib/openshift/$3/.env/OPENSHIFT_${CART_NS}_HAPROXY_REMOTING ]
then
  source /var/lib/openshift/$3/.env/OPENSHIFT_${CART_NS}_HAPROXY_REMOTING
  HAPROXY_REMOTING=$(get_env_var_dynamic "OPENSHIFT_${CART_NS}_HAPROXY_REMOTING")
  echo "export OPENSHIFT_${CART_NS}_CLUSTER_REMOTING=$list,$HAPROXY_REMOTING" > /var/lib/openshift/$3/.env/OPENSHIFT_${CART_NS}_CLUSTER_REMOTING
  rm -f /var/lib/openshift/$3/.env/OPENSHIFT_${CART_NS}_HAPROXY_REMOTING
else
  echo "export OPENSHIFT_${CART_NS}_HAPROXY_REMOTING=$list" > /var/lib/openshift/$3/.env/OPENSHIFT_${CART_NS}_HAPROXY_REMOTING
fi
