#
# Standard Tasks
#
require "../../../tasks/build_tasks"
require "../../../tasks/yard_tasks"

# Define these to allow generation of comprehensive yard docs
YARD_SOURCEROOT = File.dirname(__FILE__)
YARD_SOURCES = ['lib']

# Custom test task
require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
end

