#!/bin/bash

[ ! -z "$MONGODB_LIB_UTIL" ] && return 0
MONGODB_LIB_UTIL=true

function start_mongodb {
    super_run_as_user "$MONGODB_DIR/${application}_mongodb_ctl.sh start"
    wait_to_start
}

function restart_mongodb {
    super_run_as_user "$MONGODB_DIR/${application}_mongodb_ctl.sh restart"
    wait_to_start
}

function wait_to_start {
    i=0
    while (( ! echo "exit" | mongo $IP > /dev/null 2>&1) ||  \
             [ ! -f ${MONGODB_DIR}/pid/mongodb.pid ]) && [ $i -lt 10 ]
    do
        sleep 1
        i=$(($i + 1))
    done
}

function control_mongodb_on_dbgear {
   gear_user_and_host="$OPENSHIFT_NOSQL_DB_GEAR_UUID@$OPENSHIFT_NOSQL_DB_GEAR_DNS"
   ssh $gear_user_and_host rhcsh $OPENSHIFT_NOSQL_DB_CTL_ONGEAR_SCRIPT $1
}

function stop_mongodb {
    super_run_as_user "$MONGODB_DIR/${application}_mongodb_ctl.sh stop"
}

function start_mongodb_as_user {
    if [[ -n "$OPENSHIFT_NOSQL_DB_GEAR_UUID"  &&  -n "$OPENSHIFT_NOSQL_DB_GEAR_DNS"  &&
          "$OPENSHIFT_APP_UUID" != "$OPENSHIFT_NOSQL_DB_GEAR_UUID" ]]; then
        control_mongodb_on_dbgear start
        return 0
    fi

    ${OPENSHIFT_NOSQL_DB_CTL_SCRIPT} start
    wait_to_start
}

function stop_mongodb_as_user {
    if [[ -n "$OPENSHIFT_NOSQL_DB_GEAR_UUID"  &&  -n "$OPENSHIFT_NOSQL_DB_GEAR_DNS"  &&
          "$OPENSHIFT_APP_UUID" != "$OPENSHIFT_NOSQL_DB_GEAR_UUID" ]]; then
        control_mongodb_on_dbgear stop
        sleep 1
        return 0
    fi

    ${OPENSHIFT_NOSQL_DB_CTL_SCRIPT} stop
    sleep 1
}

function prepare_gear_for_standalone_mongodb() {
    # Find an open localhost IP
    IP=`find_open_ip $uid $uuid`

    # Create top level application symlink
    create_app_dir_symlink "$cartridge_type"

    # Create environment variables
    create_common_env_vars

    create_app_ctl_script "$cartridge_type"

    # And prepend to path variable so that mongodb app_ctl.sh script is called.
    sed -i "s#export \s*PATH=#export PATH=$CART_INFO_DIR/bin/:#" $APP_HOME/.env/PATH

    #  Add apache vhost configuration.
    export CART_INFO_DIR
    import_env_vars
    $CART_INFO_DIR/bin/deploy_httpd_proxy.sh $application $namespace $uuid $IP

    disable_stale_detection

    restart_httpd_graceful
}
