#!/bin/bash

# Destroys diy instance

function print_help {
    echo "Usage: $0 app-name namespace uuid"

    echo "$0 $@" | logger -p local0.notice -t stickshift_diy_deconfigure
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

cartridge_type="diy-0.1"
source "/etc/stickshift/stickshift-node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

setup_deconfigure "$1" $2 $3

remove_all_proxy_ports $uuid

if [ ! -d "$APP_HOME/app-root" ]
then
    echo "${application}.  Application directory doesn't exist:  $APP_HOME/app-root"
else
    disable_cgroups

    destroy_git_repo $application $uuid

    stop_app

    rm_app_dir

    rm_cartridge_instance_dir "$cartridge_type"
    
    enable_cgroups
fi

rm_unobfuscated_app_home $namespace $application

#
# Remove virtualhost definition for apache
#
rm_httpd_proxy $uuid $namespace $application
