require 'asciidoctor'
require 'erb'

guard 'shell' do
  watch(/^.*\.txt$/) {|m|
    Asciidoctor.render_file(m[0], :in_place => true, :attributes => { 'backend' => 'html5', 'stylesheet' => './stylesheets/foundation.css', 'linkcss!' => '' } )
  }
end

guard 'livereload' do
  watch(%r{^.+\.(css|js|html)$})
end
