require 'asciidoctor'
require 'erb'
require 'haml'
require 'tilt'

guard 'shell' do
  watch(/^.*\.txt$/) {|m|
    Asciidoctor.render_file m[0], :in_place => true, :safe => :safe, :template_dir => './templates', :attributes => %w(source-highlighter=coderay coderay-css=style stylesdir=./stylesheets imagesdir=./images stylesheet=foundation.css linkcss! icons=font idprefix= idseparator=- sectanchors)
  }
end

guard 'livereload' do
  watch(%r{^.+\.(css|js|html)$})
end
