= oo-install User's Guide
OpenShift Origin Documentation Project <dev@lists.openshift.redhat.com>
v2.0, July 2013
:data-uri:
:toc2:
:icons:
:numbered:

The `oo-install` utility is designed to ease the experience of a trial or basic OpenShift installation by interactively gathering the data to run a simple deployment. The current iteration of `oo-install` enables the configuration and deployment of OpenShift according to the following scenarios:

* Deploy all OpenShift components to one or more hosts
* Add a new node host to an existing OpenShift deployment

[float]
==== oo-install is a Work in Progress
This utility is currently in "Technology Preview". Technology Preview features are not supported and are not intended for production use. These features are included to provide customers with early access to upcoming product innovations, enabling them to test functionality and provide feedback during the development process. For highly available production deployments, expect to continue to craft install scripts customized to your particular environment.

[float]
==== Do I Have To Read a Manual?
In short, no. One of the design goals of the `oo-install` utility is to make this document completely unnecessary. If you are feeling bold, you are heartily encouraged to attempt to use the installer right now without any additionaly guidance. Check out https://install.openshift.com/ for the quick rundown on how to get started. If you run into problems, head back here or send your questions and feedback to the mailing lists or IRC channels mentioned on the oo-install web page.

== Before You Begin
This section covers some topics that will help you to have a successful OpenShift deployment. If you have jumped stright in with https://install.openshift.com/ and are having problems, look over this section to make sure you've got the basics covered.

=== Utility Prerequisites
You can run the OpenShift installer from any computer that has the following utilities installed:

* ruby (1.8.7 or greater)
* curl
* unzip

On most systems, you can install these by running:

----
$ yum install ruby unzip curl
----

If you want to run `oo-install` against a remote target host, you will also need the `ssh` client.

=== Where Should I Run This?
The `oo-install` utility can run on _any_ system that meets the minimum prerequisites. This is important to understand, because while you _can_ run the installer from your intended Broker host, you could just as easily run it from your own computer (as long as you have SSH access to the target host). As you are answering the installer's questions about where your Broker lives, it is actually useful to think of it the way that other hosts would see it, even if you are running the installer from the system where an OpenShift component will live.

[TIP]
====
*Remote Installation* +
If you are running the installer locally, but your OpenShift deployment will be installed on a remote system, you will need passwordless SSH access to your target host(s). "Passwordless" here means that either you are using an SSH key pair that was generated without a password, or that you are using a password manager like http://en.wikipedia.org/wiki/Ssh-agent[ssh-agent] to provide the password as necessary.
====

== Running the Installer
The `oo-install` utility has been developed to function as a standalone application. However, the easiest way to run it is by using a "curl-to-shell" command to download and execute the latest version of the installer in a single step. This section describes running the curl-to-shell command and also how to run the installer from the source code.

=== install.openshift.com
The recommended method for installing OpenShift is via a "curl-to-shell" command. From your command line, just run

----
$ sh <(curl -s https://install.openshift.com/)
----

If you want to pass arguments to the installer, include them after the whole command:

----
$ sh <(curl -s https://install.openshift.com/) -e -s rhsm -u user@company.com
----

By default, the installer runs in Origin mode. If you want to install OpenShift Enterprise, you can either run:

----
$ sh <(curl -s https://install.openshift.com/) -e
----

...or...

----
$ sh <(curl -s https://install.openshift.com/ose/)
----

[NOTE]
====
OpenShift Enterprise installations require access to Red Hat Subscription Manager or Red Hat Network, and will only succeed on hosts running Red Hat Enterprise Linux.
====

=== Running oo-install from source
If you are working on oo-install development, you can also run the installer directly from source:

1. Clone the openshift-extras repo from GitHub: `git clone https://github.com/openshift/openshift-extras.git`
2. `cd openshift-extras/oo-install`
3. `bundle install` (You only need to do this the first time)
4. `bundle exec bin/oo-install`

Because `oo-install` is built to support remote deployments, you don't need to set up a development environment on a target system in order to do this; you can clone the repo locally and run installations against remote systems directly from there.

=== Installer Command-Line Options
The complete list of options is as follows:

----
-a, --advanced-mode              Enable access to message server and db server customization.
-c, --config-file FILEPATH       The path to an alternate config file
-w, --workflow WORKFLOW_ID       The installer workflow for unattended deployment.
-e, --enterprise-mode            Show OpenShift Enterprise options (ignored in unattended mode)
-s, --subscription-type TYPE     The software source for installation packages.
-u, --username USERNAME          Red Hat Login username
-p, --password PASSWORD          Red Hat Login password
-d, --debug                      Enable debugging messages
----

==== -a / --advanced-mode
By default, the installation utility will automatically install http://www.mongodb.org/[MongoDB] and http://activemq.apache.org/[ActiveMQ] on the same system that you designate as the OpenShift Broker. If you would prefer to install these services on different hosts systems, pass the '-a' flag and you will br prompted to provide information on these other target systems. For more on "deployment roles", see TK.

==== -c / --config-file FILEPATH
The installer will look for a configuration file at the default location `~/.openshift/oo-install-cfg.yml`. If you want to use a different file, you can pass the filepath with this option. If the file that you specify does not exist, it will automatically be created with some basic settings.

==== -w / --workflow WORKFLOW_ID
If you have already configured a complete OpenShift deployment, you can run the installer without any user interaction by providing this argument and the ID of an installer workflow. For example, you can run the OpenShift full deployment workflow like this:

----
$ sh <(curl -s https://install.openshift.com/) -w origin_deploy
----

When you run the command this way, the installer will sanity check your deployment configuration, and if everything looks good it will run the specified workflow automatically.

==== -e / --enterprise-mode
In default mode, the installer will provide you with options for installing or extending an OpenShift Origin deployment. However, the same installer can be used to deploy OpenShift Enterprise by setting this switch.

==== -s / --subscription-type TYPE
_Subscription_ refers to where your openshift component RPMs are coming from. `oo-install` supports four options:

* *none* - If you have manually configured yum repos on the target hosts, and those repos already include the OpenShift RPMs, the 'none' value tells the installer to use what you have already set up.
* *yum* - Indicates that you would like the installer to create new yum repo entries for you under `/etc/yum.repos.d/`
* *rhsm* - (For OpenShift Enterprise) Tells the installer that you want to use Red Hat Subscription Manager to set up OpenShift software channels
* *rhn* - (For OpenShift Enterprise) Tells the installer that you want to use Red Hat Network to set up OpenShift software channels

The '-s' option exists to enable you to override the installer config file from the command line. This would typically be done in concert with the '-w' option as part of the setup for an unattended installation. For mor information on subscriptions, refer to TK.

==== -u / --username USERNAME
As indicated in the explanation of the '-s' option above, this option exists to enable you to override the installer config file from the command line. Currently, the '-u' setting is only meaningful in a scenario where you would be running an unattended installation (see '-w') of OpenShift Enterprise (see '-e') using the 'rhsm' or 'rhn' subscription methods.

==== -p / --password PASSWORD
See the comments on the '-u' option; this option would only be used under the same conditions.

==== -d / --debug
Enabling 'debug' mode will cause the installer to periodically dump out large volumes of information about the SSH sessions that it attempts to establish as it runs. This can be useful for debugging remote deployments.

== Configuring Your Deployment
When you run the installer for the first time, you will be asked to describe a number of items related to the OpenShift deployment that you want to set up. This whole process should be pretty self-explanatory, but here are some notes about the three main facets of the configuration process.

=== DNS
When you use `oo-install` to deploy OpenShift, the installer configures a http://en.wikipedia.org/wiki/BIND[BIND] server to run on the same host where the Broker will run. The primary function of this BIND instance is to provide lookup information for applications that are created by the users of your OpenShift system.

==== Registering OpenShift Hosts with the OpenShift DNS Instance
Depending on your lab setup, you may already have a DNS solution in place for your host systems. If not, you can opt to register your OpenShift hosts with the Broker's BIND server. This enables the hosts to look each other up by name in an environment where they may not be able to do name lookups otherwise.

When the installer asks you:

----
Do you want to register DNS entries for your OpenShift hosts with the same OpenShift DNS service that will be managing DNS records for the hosted applications?
----

...answering 'yes' will notify the installer that you want this registration to be done. If you _do_ answer yes, you will be asked a followup question:

----
What domain do you want to use for the OpenShift hosts?
----

While it is possible for you to answer this question with the same domain that you are using for OpenShift-hosted applications, it is recommended that you use a different domain.

For instance, if your domain is "mycompany.com", you might use:

* `apps.mycompany.com` for your OpenShift applications domain and
* `openshift.mycompany.com` for your OpenShift hosts domain

==== Interacting with the OpenShift DNS Instance
After installation, the Broker-based DNS server can be used separately from a larger DNS infrastructure, or easily configured to work in concert with one.

*To experiment with the OpenShift DNS instance without full DNS intergation* +
On a client-by-client basis, you can do the following to work against the OpenShift DNS server:

1. On the client system, make a backup copy of `/etc/resolv.conf` +
+
----
$ cp /etc/resolv.conf /etc/resolv.conf.bak
----
2. Open the file with a text editor +
+
----
$ vi /etc/resolv.conf
----
3. In the editor you will see something similar to this: +
+
----
domain mybu.mycorp.com
search mybu.mycorp.com mybu.mycorp.com. mycorp.com.
nameserver 1.1.1.1
nameserver 1.1.1.2
----
+
    * Modify the `domain` and `search` values to match the app domain (and optionally also the OpenShift host domain) that you specified. 
    * Then change the first `nameserver` entry to point to the Broker host's IP address.
    * You can remove any additional `nameserver` entries.
+
4. No restart necessary; you should be able to point a web browser on this client system at the URL off an application in the app domain. If you've also registered the OpenShift hosts with OpenShift DNS, they should be reachable by name as well.

[WARNING]
====
* Once modified to use the Broker DNS, your client system will not be able to resolve non-OpenShift-registered hostnames until it is reverted to its original settings.
* On a reboot, the client machine may overwrite your changes to the /etc/resolv.conf file
====

*To integrate the OpenShift DNS instance into a larger infrastructure* +
For a more permanent solution, here's how to delegate the OpenShift application domain (and if applicable, host domain) from your main DNS service to the OpenShift DNS server. The gist of the work is that you will be telling your main DNS service to _delegate_ to the OpenShift DNS service based on the domain of the name to be looked up.

1. 
2.
3.

=== Host Instances and Roles

=== Subscription

== Troubleshooting
