#require "bundler/gem_tasks"
require 'rake'
require 'rake/testtask'
require 'rcov/rcovtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
end

desc "Coverage tests"
Rcov::RcovTask.new  do |t|
  t.libs << 'test'
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
end
