#!/bin/bash
# openshift-iptables-port-proxy
#
### BEGIN INIT INFO
# Short-Description:  Script to apply the openshift port proxy iptables rules.
# Description: Script to apply the openshift port proxy iptables rules.
### END INIT INFO

start() {
    ROUTE_LOCALNET=`sysctl -n net.ipv4.conf.all.route_localnet`
    if [ $ROUTE_LOCALNET -eq "0" ]; then
        echo "WARNING: net.ipv4.conf.all.route_localnet must be enabled." 1>&2
        sysctl -w net.ipv4.conf.all.route_localnet=1
        echo "WARNING: It has been temporarily enabled.  Please ensure this setting is persisted in /etc/sysctl.conf."
    fi

    if [ -f /etc/openshift/iptables.filter.rules ]; then
      { echo "*filter"; cat /etc/openshift/iptables.filter.rules; echo "COMMIT"; } | iptables-restore -n
    fi

    if [ -f /etc/openshift/iptables.nat.rules ]; then
      { echo "*nat"; cat /etc/openshift/iptables.nat.rules; echo "COMMIT"; } | iptables-restore -n
    fi
}

stop() {
    # Droping the reference from the input chain would needlessly complicate
    # this logic.  For that reason we can't actually drop the chain.  This will
    # allow admins to flush the chain if needed.
    iptables -F rhc-app-comm
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    reload)
	# Calling stop could cause an outage.  It's best to simply call start.
        start
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|reload}"
        exit 2
esac
