#!/bin/bash

# Publishes the endpoint for this gear. Output format = $uuid@$dns:$appname

# Exit on any errors
set -e

# Get gear ip address.
if ! gip=$(facter ipaddress); then
   gip=$(python -c "import socket; print socket.gethostbyname('$(hostname)')")
fi

#
# Publish this gear's endpoint.
# 
echo "${OPENSHIFT_GEAR_UUID}@${gip}:perl;$OPENSHIFT_GEAR_DNS"
